### ISSUE TITLE
Help with fork

### ISSUE THREAD

**Issue by zoreu** [elgatito/plugin.video.elementum#1020]
How do you generate binaries for various platforms? Without knowing how to do it, it's difficult to fork and create something similar

**Comment by elgatito** [comment]
@zoreu It is described in README file of the binary part: https://github.com/elgatito/elementum?tab=readme-ov-file#how-to-release

**Comment by antonsoroko** [comment]
@zoreu 
To get full understanding of how to build elementum, I would suggest you to read Readme, Makefile, *.sh scrips in both [python](https://github.com/elgatito/plugin.video.elementum) and [golang](https://github.com/elgatito/elementum) repos. It helped me, at least.

Although, despite the messaged about "Development of this addon has been stopped" addon is still supported quite well, so if you want to implement some feature or fix something - it makes more sense to make a "pull request" instead of a fork. 

Of course if you want to create your own addon that would be significantly different from elementum - then please create a fork.

Anyway, any development help is appreciated.

**Comment by antonsoroko** [comment]
also, there is a conversation and some advanced tips (about libtorrent-go + SWIG for example) here:
https://github.com/elgatito/plugin.video.elementum/issues/712
