### ISSUE TITLE
Why can't elementum  paste magnet link to url download ? Please support it.

### ISSUE THREAD

**Issue by i990049** [elgatito/plugin.video.elementum#1070]
I have to transfer the private tracker torrents through APP to my tv box every time.It seems brust doesn't works here.

**Comment by antonsoroko** [comment]
@i990049 it is hard to understand what you really mean - elementum supports magnet links, burst supports private trackers. when you write issue - you should elaborate what you mean. there is no sense to be greedy for words.


1. you can add magnet link via "add torrent" in elementum WEB UI, open "Status" page in elementum main menu to see the URL
![Screenshot 2024-10-07 at 14-01-17 Elementum Web UI](https://github.com/user-attachments/assets/fa8ed28f-bc9e-48d8-9020-013742cc8ab7)

2. you can add magnet link via "add torrent" in elementum main menu (you can paste URL via some "Kodi remote app", i believe)
![Screenshot_20241007_140958](https://github.com/user-attachments/assets/4efd0ceb-55eb-45f4-a31f-8d80adde879c)


3. if your private tracker not in burst - then you can add it to burst. thus you do not have manually add torrent.
alternatively, you can ask in burst repository (in issues) to add your tracker - if it is a useful tracker (and without paid subscription and etc) - then someone maybe can add it. otherwise - you would need to add it yourself.


**but you must know that if torrent is marked as private then it can't be shared via magnet link.**
usually private trackers use private torrent, thus they do not provide magnet links.
but maybe your tracker is private, but their torrents are not private. you can see if torrent is private in some desktop bittorrent app.

**Comment by i990049** [comment]
What do [A..M][N..] mean？I have PT acount and enter user name and password. I thought Burst can use PT acount to search video just like public track, but it didn't, if elementum can't why it requires name and password? Now I have to transfer PT torrent files from smart phone to TV box every time to stream video. I noticed elementum peer id changed from -GT0001- to -LT1xxx-, it will be acceptable by more PT and BT clients.
![屏幕截图(291)](https://github.com/user-attachments/assets/0dd0ec58-ec85-474d-9aba-14a5f59efd43)
![屏幕截图(292)](https://github.com/user-attachments/assets/cae1bce0-e0f2-4684-9745-043cbf2c87da)

**Comment by elgatito** [comment]
@i990049 Elementum does not have own UI controls, it is controlled by Kodi (and you cannot change it). Pasting is part of Kodi, as well.
You can use Yatse android app to send links to Kodi. I think it will automatically send torrents to Elementum in that case.

**Comment by i990049** [comment]
Why burst require to enter the user name and pastword of private tracker？if it can't search and RSS then for what？what does 0.1.106 update？

**Comment by elgatito** [comment]
> What do [A..M][N..] mean in the second screenshot?

List of all the tracker websites that Burst supports.

> Why burst require to enter the user name and pastword of private tracker？

To search on private tracker (or to download a torrent) - you need to authorize yourself, that is why you need to put your credentials.

> if it can't search and RSS then for what？

To search for specific torrent file for specific Movie/Episode. Elementum is not torrent-centric. 
It is not about tracking torrent updates or new torrents. 
There are better tools for that.

**Comment by i990049** [comment]
how to search for specific torrent file for specific Movie/Episode of private tracker on elementum？

**Comment by antonsoroko** [comment]
@i990049 

4.
> I noticed elementum peer id changed from -GT0001- to -LT1xxx-, what's the peer id of elementum 0.1.105?

since 0.1.104 it is "-LT1100-" (libttorrent ID, because elementum uses [libttorrent library](https://www.libtorrent.org/))
https://github.com/elgatito/elementum/blob/v0.1.104/util/ident/ident.go#L50
before 0.1.104 it was "-GT0001-" (leftover from very old times when elementum used "anacrolix/torrent" library)
https://github.com/elgatito/elementum/blob/v0.1.103/util/ident/ident.go#L50
https://github.com/anacrolix/torrent/blob/master/version/version.go#L15

>it will be acceptable by more PT and BT clients.

what do you mean? please paraphrase. 
i think libtorrent ID is much more common (thus more "acceptable") than "anacrolix/torrent" ID.

5.


>I have PT acount and already enter user name and password. I thought Burst can use PT acount to search video just like public track, but it didn't

again, to use specific "private tracker" you must enable it in burst.
if tracker is not supported - either add it to burst youself (you need to know some HTML for that) or create issue in burst repo and ask to add it.  **i already described that in details in my first message**.

if tracker is already in burst but it does not work - then either 
a. **create issue** in burst repo
b. [fix appropriate code](https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json) (maybe URL was changed or HTML page layout was changed) and make PR.

**Comment by antonsoroko** [comment]
@i990049 

>anacrolix/torrent was banned by the soft

then it is good that we do not use anacrolix/torrent ID anymore. as i said we use libtorrent ID.

>Have you compared these codes libtorrent4j(JAVA)/Monotorrent(c#)/libtorrent? which is best？

no.

>what code is elementum?

golang. but for bittorrrent part elementum uses libtorrent (super famous c++ library). 

>does it support BitTorrent 2.0 and WebTorrent？

we use libtorrent 1.1. search in internet if it supports what you need.

**Comment by i990049** [comment]
Only libretorrent 2.x support BitTorrent 2.0 and WebTorrent, but most private trackers don't support libretorrent 2.x. So elementum only support BitTorrent 1.0, why not use the latest libretorrent 1.2.x? As webtorrent, you can try on watchsomuch with webtorrent desktop and elementum. I suggest elementum add this public tracker, it is the successor of 7tor.org.ALL private tracker made by Unit3d can use Elementum.
https://watchsomuch.unblocked.how/
https://github.com/webtorrent/webtorrent-desktop

**Comment by antonsoroko** [comment]
@i990049 
>Only libretorrent 2.x

elementum uses libtorrent, not lib**re**torrent.

>why not use the latest libtorrent

because elementum is written in golang, and libtorrent is written in C++. those are 2 different languages.
so elementum has to use intermediate layer - https://github.com/ElementumOrg/libtorrent-go written in [SWIG](https://en.wikipedia.org/wiki/SWIG).
thus, to update to libtorrent 2 someone who knows c++ should update all "bindings" in libtorrent-go repo.
and then update golang code accordingly.
and this is a big amount of work. 
but there are some other SWIG binding in internet that can be used as reference for update.
https://github.com/frostwire/frostwire-jlibtorrent/tree/master/swig
https://github.com/aldenml/libtorrent4j/tree/master/swig

anyway, so far - nobody offered help in this direction.

>As webtorrent,

I think there is some confusion.
WebTorrent is just a torrent client. it is not a protocol (like BitTorrent, or BitTorrent 2.0).
Elementum is a torrent client as well.
So, elementum can't support WebTorrent, since it is not a protocol but an application.
Same way that firefox can't support google chrome.
i mean: your question about "does elementum support WebTorren?" is incorrect since it makes no sense.

>ALL private tracker made by Unit3d can use Elementum.

Again, I think there is some confusion.
Elementum is a torrent client. it is not about tracker. elementum knows nothing about tracker. it only cares about torrent file.
Burst, on the contrary, interacts with trackers: login, search, download .torrent file.

Unless you wanted to say that Unit3d do not block elementum as client.

>watchsomuch

Burst supports adding of "classic" trackers, that provide results like table with all the info (size, quality, number of seeders and etc), burst does not support "just a website with torrent files".

>Unit3d

btw, if the tracker that you use is not in Burst and you do not know HTML to add it, you can install [Jackett](https://github.com/Jackett/Jackett/) server (or you can find public jackett server) and then use this addon to connect elementum and jackett:
https://github.com/fugkco/script.elementum.jackett

list of some trackers that jackett supports:
https://hdvinnie.github.io/Private-Trackers-Spreadsheet/

**Comment by i990049** [comment]
Sorry I didn't make it clear.
https://github.com/arvidn/libtorrent/issues/223
WebRTC is a a protocol also refer as webtorrent protocol.

Webtorrent desktop
is a bittorrent client both support BitTorrent 2.0 and WebTorrent protocol/WebRTC just like libretorrent and bigly BT. You can try it on stream site Watchsomuch.
https://github.com/webtorrent/webtorrent-desktop

libtorrent 2.x 
is a protocol both support BitTorrent 2.0 and WebTorrent protocol/WebRTC

libtorrent 1.x doesn't support BitTorrent 2.0 and WebTorrent protocol/WebRTC
the latest version is 1.2.x, elementum use 1.1.x.

Torrent files of private trackers such as Nexusphp/Unit3D/Gazelle don't support BitTorrent 2.0/Hybrid protocol.
Nexusphp/Gazelle blocks Elementum as defaults, Unit3D allow Elementum as defaults. So if you want to stream torrent files from Private Trackers, sites made by Unit3d will be Ok, just let Elementum open the torrent file of Unit3D sites.

libretorrent
is a BT client using libtorrent 2.x and based on libtorrent4j. If you want some help, take a look at it. Maybe it's helpful for Elementum to support BitTorrent 2.0 and WebTorrent protocol/WebRTC in the future.

**Comment by antonsoroko** [comment]
you are right, looks like libtorrent has support of WebTorrent https://github.com/arvidn/libtorrent/pull/4123
but for some reason it is only in master (test) branch, not in version 2. and even in master it is disabled by default.

https://github.com/arvidn/libtorrent/blob/1d644d19cb916261f651458aa5990b9fe1017299/CMakeLists.txt#L733
https://github.com/arvidn/libtorrent/blob/v2.0.10/CMakeLists.txt

but anyway, it is good to know about this feature. thank you.

**Comment by i990049** [comment]
How about libretorrent 3.x using libtorrent 2.x and based on jlibtorrent and libtorrent4j? Does it enable WebRTC as default? Is the SWIG of it helpful to you?
https://github.com/proninyaroslav/libretorrent

**Comment by antonsoroko** [comment]
libretorrent is a client (and only for Android, while Elementum supports many OS), not library. So it can't be used.
And anyway to migrate to a new library - it would take a lot of work. 
Easier to to update to a new libtorrent version. 
But again, there are no volunteers to do that.

**Comment by i990049** [comment]
Monotorrent is also library, take a look at it.
https://github.com/alanmcgovern/monotorrent

**Comment by antonsoroko** [comment]
>MonoTorrent, a bittorrent library for **.NET** 

elementum is written in Golang. So it can't be used.

and as i said above:
>And anyway to migrate to a new library - it would take **a lot of work**.
>Easier to to update to a new libtorrent version.
>But again, there are no volunteers to do that.

**Comment by elgatito** [comment]
@i990049 

> Hoping this can help you.

Sorry, help with what? Nobody will migrate to another library. Unless you want to contribute and make everything.

**Comment by antonsoroko** [comment]
@i990049 everybody use libraries :-) they sped-up development dramatically.

libtorrent was always used by XBMCtorrent -> Pulsar -> Quasar -> Elementum.
(parent -> child)

libtorrent does all the bittorrent things for elementum - download, upload, communication with tracker (i mean not web tracker like website, but bittorrent tracker server), DHT, etc.

elgatito also wrote custom c++ code that implements memory as download storage, libtorrent does not have such feature. 

(although anacrolix/torrent supports memory as storage, thus at some point elgatito migrated from libtorrent to  anacrolix/torrent, but download speed was low , thus elgatito migrated to back libtorrent.)

for elementum - updating libtorrent version means: update swig code, updating custom c++ code that implements memory as download storage, update golang code, test everything.
it is possible, but nobody want to do this because current version of libtorrent works just fine for our use cases (e.g. when you download video from popular public trackers like piratebay or torrentglaxy or some private tracker like rutracker - they all support  bittorent v1 protocol).

(migrating to new library means even more work - that's why elgatito said that nobody will do this.)


i hope this clarify things. because i think i have nothing more to add. i told you everything :-)

**Comment by i990049** [comment]
Is there any blackberry/iOS/tvOS/webOS version of elementum? I didn't find it. Kodi has these version.

**Comment by antonsoroko** [comment]
For webos - armv7_softfp build. 
Use search in repo for word "webos" for details.
You will find https://github.com/elgatito/plugin.video.elementum/issues/939 for example.

**Comment by i990049** [comment]
is it possible to support iOS/tvOS？

**Comment by antonsoroko** [comment]
No. Please use search in repository to find out why. This was answered many times. 

But maybe Elementum can run on iOS/tvOS if you enable "force run as library" option in advanced settings, but I do not have such device to test it.

**Comment by elgatito** [comment]
To make a build for tvOS/iOS (which are Arm) you need to make a proper image for:
- https://github.com/ElementumOrg/cross-compiler
- https://github.com/ElementumOrg/libtorrent-go
- and then use both for compiling https://github.com/elgatito/elementum

I could not make it and I don't have a device to test it (maybe even if you make it - it won't run on tvos/ios just like it does not on Xbox platform, due to platform limitations).

Feel free to make it and contribute to Elementum. Would be happy to review and merge it.

**Comment by elgatito** [comment]
Closing this issue, as was initially about pasting something into Elementum.

Elementum through Kodi uses Kodi's UI elements and controls and cannot enable/disable pasting, it is controlled by Kodi.
For Web part you can paste anything into Elementum through browser.
