### ISSUE TITLE
[Request] Not showing movie if no streams available

### ISSUE THREAD

**Issue by zorvalth** [elgatito/plugin.video.elementum#159]
Is it possible to not showing the movie in the library if there is no streams available? Lets say I add a movie which will be released in the next few months. I have to check manually its streams availability to see is it released yet. If there is some way to add the strm files in some temp folder and the addon to check its streams availability every day and if there are any then move it to the library folder?

**Comment by elgatito** [comment]
Sorry, but no.
Your request needs to run searchers, and they are external plugins, and so somehow need to store library in plugin and then create strm files or filter the movie/episode.

**Comment by zorvalth** [comment]
Ok, at least do you have any idea for a work around if I have 50 upcoming movies in the library how to figure it out which are released without click on every single one of them?

**Comment by elgatito** [comment]
Sadly, there is no way to do that. 

I will re-open this issue, as a feature, to run searchers to know if there is any stream, then save that state in the database. 

But there is a chance to get ban from providers, because you will generate a lot of queries for any non-searched, yet, item.

**Comment by zorvalth** [comment]
Even if its once per day? How does the TV shows work? As far as I checked it doesn't show the next episode in the library if its not yet released or I'm wrong?

**Comment by elgatito** [comment]
@zorvalth TVShows are simplier, because they have an Aired date, and they are sure to be available the next day, BUT, if you search for an episode with translation - you will have the same problem, as you have with movies, they are not available on the next day and you have to wait for it.

Each movie needs a separate search to provider. If you have 50 movies in the library that wait to be found, then it's 50 queries (at least per day), but if you have hundreds of movies - it can be a problem.

**Comment by zorvalth** [comment]
Is it pssible to fetch dvd/blue ray release day and activate queries searches 2-3-4 weeks before that?

**Comment by untoreh** [comment]
@zorvalth i think for your use case tools like sonarr are better suited

**Comment by Xperplay** [comment]
@elgatito 

Possibly more efficient/reliable to query a pre database instead of providers directly. I use predb.me but there are others.

Unreleased Movie example
https://predb.me/?search=sicario+2018&cats=movies

Released Movie example
https://predb.me/?search=sicario+2015&cats=movies

Still as you said separate search for every movie but it should be more efficient as you`re  only checking one source. Also searches can be refined further than the example provided for instance you could grab the release types and additional keyword filters from elementum burst settings and pass them along the query. https://predb.me/?page=searching

**Comment by elgatito** [comment]
Closing this. It will make too many requests to trackers, then they are banning users.

**Comment by antonsoroko** [comment]
as a note: elementum has autosearch feature (for a while) that can be used for similar use cases.
