### ISSUE TITLE
Wrong scrobbling after adding Trakt account in Elementum

### ISSUE THREAD

**Issue by konvar** [elgatito/plugin.video.elementum#243]
If I reinstall elementum and don't add the trakt account in elementum don't get this problems (official trakt plugin is installed).
This is what happened on my trakt account after adding trakt in elementum. https://imgur.com/a/5caCF35 After i watched 1 episode of Code Black he indexed twice on trakt and added other shows i've watched a long time ago.

If you do not understand the problem, I can write more tomorrow.
Thank you very much!

## Your Environment

* Version used: 0.0.61

* Environment name and version: Kodi 16.7
 
* Operating System and version: Windows 10 X64

* Link to Kodi debug log: http://paste.ubuntu.com/p/WGXYz6Rj95/

**Comment by elgatito** [comment]
Try to disable official Trakt addon and try again.

**Comment by OakSorcerer** [comment]
Yep, disable official addon, it doubles watched status sometimes. Your problem still exists. This happens if you mark some of your episodes or seasons "as watched" from Kodi library. Then a huge amount of episodes appears as watched in the history of trakt.tv site. It seems that watched status for shows is broken, cause none of the watched episodes synch back to Kodi library and that's what happens if you try to mark an episode "as watched" from Kodi interface. There is no such problem for movies. I can recommend you using this tool to fix your trakt.tv history http://www.brendanspijkerman.nl/trakthistorymanager/
