### ISSUE TITLE
Kodi localization bugs elementum lists

### ISSUE THREAD

**Issue by miromiric1** [elgatito/plugin.video.elementum#372]
Dont know if its same with other kodi localizations, but if you use kodi in croatian, elementum lists dont work, cant be opened. fix: use english. also would be nice if its possible, like in other kodi video addons, to have list with years so if you want lets say movies from 2018 you select year 2018.

**Comment by elgatito** [comment]
There is already an issue regarding Croatian language. #270. 
It looks like a bug in Kodi in general, because plugin does not have anything special with this language. But then I switch Kodi to Croatian localization - it stops working good (not in plugin, but in general).
Like some characters are not processed fine.

**Comment by elgatito** [comment]
@miromiric1 Please, try v0.1.30.
