### ISSUE TITLE
Questions on Amazon Fire TV 4k

### ISSUE THREAD

**Issue by Nukles** [elgatito/plugin.video.elementum#437]
I am considering to buy an Amazon Fire TV Stick 4k and install Kodi. Do you know if I can stream 4k movies with Elementum with it?

Here are some specs (from https://forum.kodi.tv/showthread.php?tid=336151)

RAM - 1.5GB DDR4
Storage - 8GB NAND Flash
Micro USB 2.0 for power or optional 100Mbit Amazon Ethernet (100Mbps) Adapter (not-included)
WiFi - Dual-band, dual-antenna Wi-Fi supports 2x2 MIMO 802.11a/b/g/n/ac - MediaTek MT7668

**Comment by elgatito** [comment]
Elementum is only downloading files and giving it to Kodi. 
If you have enough speed for downloading big 4K files - then it depends on the device, whether it has enough CPU power and so on.

**Comment by elgatito** [comment]
@Nukles if device supports hardware 4k decoding - then you just need appropriate download speeds to be able to downloaded file pieces in-time.

**Comment by soulnull** [comment]
> 
> 
> I am considering to buy an Amazon Fire TV Stick 4k and install Kodi. Do you know if I can stream 4k movies with Elementum with it?
> 
> Here are some specs (from https://forum.kodi.tv/showthread.php?tid=336151)
> 
> RAM - 1.5GB DDR4
> Storage - 8GB NAND Flash
> Micro USB 2.0 for power or optional 100Mbit Amazon Ethernet (100Mbps) Adapter (not-included)
> WiFi - Dual-band, dual-antenna Wi-Fi supports 2x2 MIMO 802.11a/b/g/n/ac - MediaTek MT7668

Sorry to necro this post, elgatito, but I figured I'd chime in here with some more info for Nukles.

I use Elementum currently on a gen2, which is slightly more powerful than the stick.

It runs, but due to needing to cache a torrent to ram as it's playing, it tends to run low on system RAM, causing it to occasionally freeze/jerk forward in the video (the freeze is usually about a second or two, then it rushes forward to catch back up. Audio is unaffected). It happens maybe once every 15-20 minutes during playback, so it's not a deal-breaker, but notable. This'll likely be more pronounced on the stick, as it has 512mb less ram, so will likely happen more often.

Have tried to get disk caching working using an SD card to mitigate this, to no avail. I believe the random read/write in such a rapid manner overloads the IO controller, and causes elementum to stop downloading while the android (FireOS) IO scheduler catches up with the actual data being written.

Playing from RAM is your only real option, and it's not bad, but there are occasional hiccups. You'll want to prefer torrents with 100+ seeds, else you'll find it stopping to buffer the file, or it may take forever for the video to start.

Honestly, if you're looking for a box specifically for kodi, consider either the Vero4k (designed around Kodi, directly runs it out of the box) or, if you're willing to do some work to save some money, there are no shortage of cheap "android tv" boxes you can put libreelec/coreelec onto. I love my Sunvell T95z running coreelec. $50 USD, has an excellent processor, 2gb of ram, and runs elementum flawlessly without any hiccups. Spent about 20 minutes to get it running. If you can follow instructions and copy files to USB sticks/SD cards, it's pretty easy. Seriously, go to coreelec's site (google it), pick a random box and look at the instructions, see if maybe it's something worth taking a crack at. Either way, most of the cheap android tv boxes have a Kodi clone already installed, but honestly.. Kodi on Android/FireOS isn't ideal. Performance is much better running directly on the box, and not through Android.

Just figured I'd chip in a bit here having experience with a few different boxes, and honestly, while the FireTV was my first Kodi experience, I rarely use it anymore. Technically a bit more powerful than my T95z, but worlds different in the quality of the experience in using Kodi.

Hope this helps.
