### ISSUE TITLE
Leaving the source list stops playing other content

### ISSUE THREAD

**Issue by riegaz** [elgatito/plugin.video.elementum#448]
2 issues:

Leaving the sources list stops streams playing in the background.

https://send.firefox.com/download/5b251dea43b9d157/#eDsQE8FE_Kr3vQ7qp955gw

Leaving the sources list sometimes shows an error message for no reason. Happens in the lasst seconds oft the following video

https://send.firefox.com/download/d69d262b9297bbce/#BObQFbiMZSHyK3Y_2ghryQ

Minor issues but they become annoying.

Thanks

**Comment by elgatito** [comment]
What is "sources list"?

**Comment by riegaz** [comment]
I call the list of available torrents the sources list. Sorry for the confusion.

**Comment by elgatito** [comment]
When you search for something - Kodi expects to get stream link in the end. When you cancel stream selection - Kodi does not get a stream and shows error.
That is the reason why "current" player stops, because Kodi expects to replace it with a new stream.

I do not know of a way to overcome that and have no plans to do that, that is not a bug from plugin's side.

**Comment by riegaz** [comment]
Okay. Thanks for letting me know. I still think it is an unwanted behavior, but if it can't be solved I can life with it.

**Comment by elgatito** [comment]
You can't change it, it's from Kodi, that expects to get video stream and does not get it, so showing an error.
