### ISSUE TITLE
Buffer size settings not working

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#455]
I want when i start movie or tv show episode and elementum starts downloading the pre-buffer size, the pre-buffer size that have to be downloaded to be no more than 20mb. I have disabled 'Choose memory size automatically' option, and for "Memory size to use for each torrent' i set 20mb, but these settings doesn't seem to have any effect, because elementum chooses different buffer size on its own every time, and its more than 20mb, in the range between 20mb and 80mb, or more. Why is this happening?

I am using Kodi 17, Elementum 0.1.35 and Windows 7 x64.

**Comment by elgatito** [comment]
1) Please, do not create issues without providing logs, if you suspect you found a bug.
2) Setting Buffer to 20mb does not mean it will be strictly 20mb, because torrent consists of pieces, and buffer should consist of complete pieces (which can be even 8mb or 16mb). And also there should be 5mb downloaded from the end of the file, it is needed by Kodi.
3) If you have enabled automatic buffer adjustment setting - you buffer can be increased to give more stable playback for Kodi.

**Comment by peter099** [comment]
Thanks, for the answers. Can you, please, explain, why Kodi needs the last 5mb of the file? Is this just for torrents?

**Comment by elgatito** [comment]
@peter099 it does not need exactly 5mb, but it needs some bytes, depending on the codec, you don't need how much will it need, so 5mb is enough usually for any video file.

**Comment by peter099** [comment]
Thanks. Where elementum stores the .torrent files when the settings are to use the ram memory?
