### ISSUE TITLE
[Request] Start the stream after 10mb of the torrent is downloaded

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#504]
Popcorn Time starts the stream after 10mb of the torrent is downloaded, no matter the size of the torrent. Why this can't be done with elementum?

**Comment by antonsoroko** [comment]
If I remember correctly you can set initial buffer to any number in settings. Also there is buffer in Kodi itself and (If I remember correctly) appropriate setting in elementum that increase elementum's buffer to match Kodi's buffer it elementum's buffer is smaller.

**Comment by peter099** [comment]
Yes, there are buffer and other settings, but they do nothing whatever settings i choose. Elementum is selecting different buffer size for each torrent by itself. For most of the torrents it downloads 40-50mb before start streaming and for some even 100mb. Whatever settings i try i can't make it to start the streaming after 10mb of the torrent is downloaded.

**Comment by vtolstov** [comment]
yes, i have the same issue - sometimes it downloads 20Mb, but most of the time 45-52Mb

**Comment by elgatito** [comment]
Torrent consists of pieces. Pieces can be up to 16Mb size. So if we want to download first 10mb and last 8 mb - we will have to download 16+16mb.
When you download file from many-files torrent - start of a file can be part of another file's ending, so you can even have 16*2+16*2 for downloading same 10+8mb pieces.
And so on.
So we are downloading full pieces, not just part of them.

Minimal sizes are taken from experience, to avoid having Kodi player to wait until another Mb is downloaded (because it can get a timeout). Of course it can be fine with downloading only 8Mb, but it is often easier to download another 8mb then to get a timeout and start from the beginning.

**Comment by elgatito** [comment]
@peter099 you can set any buffer in Elementum settings. There is no minimum requirement. 
In the next version you will get new setting to change end-of-file buffer size as well.

**Comment by elgatito** [comment]
@peter099  in v0.1.43 you can change buffer sizes for both start and end of file.
