### ISSUE TITLE
Elementum freeze on CoreELEC

### ISSUE THREAD

**Issue by sinisab89** [elgatito/plugin.video.elementum#522]
I tried watching a tv show and 5min into the show video and audio started stuttering then buffering and after a few moments tv box completely froze. I had to unplug the power source to restart it. TV box is Tanix, s905w running latest CoreELEC on sd card, Kodi Leia. I chose torrent, download started normally (buffer set to 200mb, file storage), playback started normal too and 5min into the video it started buffering (altough 80% of the video was already downloaded). It tried to continue a few times, only for a second and then completely froze my box.

Kodi log: https://pastebin.pl/view/7233978b

**Comment by sinisab89** [comment]
Today I downloaded the latest CoreELEC version, formated the sd card, reinstalled it completely and installed only Elementum addon. Configured it to save to file and this time I got "Source is too slow" error popping out with video stuttering and freezing. Switched Elementum to memory storage and watched about 2 hours of video today without buffering, stuttering or anything. Guess that torrenting and watching a video from sd card at the same time is just too much for card to handle. Sorry I brought the issue up, didn't know what was happening because "Source is too slow" didn't came up before and I didn't see anything that suggested a problem with sd card transfer rates in kodi.log.

**Comment by RaulGuichard** [comment]
I have had this problem on several SBCs, as you state it seems that it is too much for the SD card to handle. My solution besides using memory (which has some cons since the buffer size is limited to the size of the free memory) is to **use an external drive connected via USB 3** (I formatted it to ext4 for performance but I guess you could you exFat or NTFS) and set Elementum to store the files in that drive. I have been perfect since then.

PS: I have been using an old laptop drive with a USB enclosure, you can get fancier with SSDs but I think for most scenarios it will be overkill.
