### ISSUE TITLE
Elementum doesn't show all the results

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#573]
I didn't know if it relates to Elementum or Burst, so I opened it here.
According to the log I see there is other results that doesn't show in the Results screen,

Steps:
1. Make a manual search for this: "Money Heist S04E02"
2. According to the log there should be more results that returnd from the other providers.
But I getting only this few (5 results) according to the screenshot that I have attached.

Kodi debug log:
https://paste.ubuntu.com/p/pWdtddfxb3

Screenshot:
![image](https://user-images.githubusercontent.com/13424257/80151169-479f6700-85c2-11ea-99aa-fea1de6201a4.png)

Thanks.

---
Kodi 17.6
Elementum 0.1.51
Elementum Burst: 0.0.48
Win 10, 64 bit

**Comment by I-Cat** [comment]
ooooh

**Comment by antonsoroko** [comment]
There is an option in burst that allows you to show torrents without seeds. (Alongside with other filters).
Might be the case here since this torrent does not have many seeds (in general) and if i am not mistaken - burst  gather number of seeds not from websites but by querying trackers, so what you see on website might be "stale" number and in reality burst will think that torrent does not have seeds and will filter it out.

**Comment by elgatito** [comment]
@burekas7 you can read the log, there are messages why some items are removed. Cloudflare, 404 error, resolution not allowed and others.

**Comment by burekas7** [comment]
Thanks. I wasn't sure at first if these results are before or after the filter.

But I still have an open issue with the results that I have tested vs a clean kodi.
https://github.com/elgatito/script.elementum.burst/issues/157#issuecomment-619562047

**Comment by burekas7** [comment]
Fixed on Elementum Burst 0.0.57
More details here: https://github.com/elgatito/script.elementum.burst/issues/224
