### ISSUE TITLE
bad status getting error 403 - Issue on KODI

### ISSUE THREAD

**Issue by jffp1101** [elgatito/plugin.video.elementum#627]
## Current Behavior

Upon navigating to Movies>>Popular Lists or any sections.. I am getting this msg BAD STATUS GETTING TOP LIST: 403

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 
Kodi ver: 0.1.58 - Leia 18.8

* Environment name and version: 
Kodi ver: 0.1.58 - Leia 18.8

* Operating System and version:
Nvidia Shield Android TV ver 9.

* Link to Kodi debug log:
https://paste.kodi.tv/aleborokor

**Comment by splitfirex** [comment]
same here, i guess its the trakt token expired

**Comment by elgatito** [comment]
I had no notifications about expired/deleted ClientID. And it looks like for some people it is working, for some - not.

**Comment by KillerJoeBR** [comment]
It happened to me. So I had to create my own trakt api keys which is quite complicate for the average person. But it works now

**Comment by jffp1101** [comment]
> It happened to me. So I had to create my own trakt api keys which is quite complicate for the average person. But it works now

Nice! Care to share steps on how to’s?

**Comment by syneoa** [comment]
Confirmed working after creating Kodi API key and re-authorize trakt again.

**Comment by shmizan** [comment]
I get the same message.
@syneoa and @KillerJoeBR care to share a short step list for that?

**Comment by gudge25** [comment]
hi there  i am using Elementum in LibreElec ISO  (home cinema small  PC)  and there is no way to copy pacte API  to Elementis settings 
is there a way to  edit SOME conf file of elementum over ssh  
Regards

**Comment by elgatito** [comment]
@gudge25 Edit `settings.xml` file inside `plugin.video.elementum` directory.
https://kodi.wiki/view/Userdata

**Comment by ShlomiD83** [comment]
> I get the same message.
> @syneoa and @KillerJoeBR care to share a short step list for that?

https://koditips.com/create-trakt-api-key-kodi-addon/

**Comment by jffp1101** [comment]
I was able to follow this instructions and work fine with me now! Here's the steps: 

How to Create Your Own Trakt API Key:

    Click here:
    https://trakt.tv/oauth/applications/new
    To go to the Trakt API application signup form. You’ll have to sign in to your Trakt account, so create one if you don’t have one yet and then make sure you are redirected to a page with the heading “Create a Trakt.tv API App”.

    Fill out the form as follows:
    2.1 Give your API a name.
    2.2 Don’t worry about entering in an icon.
    2.3 Give your API a description.
    2.4 Enter in a redirection URL of "urn:ietf:wg:oauth:2.0:oob" or "http://www.google.com"
    2.5 Leave the Javascript origins blank
    2.6 Make sure /checkin and /scrobble are checked
    2.7 Click the Save Button

    Copy and paste your "Custom Trakt API Client ID" and "Custom Trakt API Client Secret" in Elementum -> Settings -> Trakt.

    Reauthorize your Trakt account in Elementum's settings. Then Restart your Kodi. ! works!

**Comment by kauly** [comment]
Who will make a PR to fix this?

**Comment by JacopoV** [comment]
Confirmed here too. Working after API key and re-authorize trakt again.

**Comment by pitsi** [comment]
I noticed the above behavior today! I usually open the tv shows > recent episodes menu when I use elementum, so all the above went unoticed all these days. How can I fix the forementioned functonality without a trakt account? I do not have and I am not willing to make one.

I would not mind if there were 1-2 submenus that are not working without it, but it affects almost every single one under tv shows (trending, most popular, most played, most watched, most collected and most anticipated) and movies (popular lists, trending, most popular, most played, most watched, most collected, most anticipated and box office)!

**Comment by crmagicxxx** [comment]
Why this issues is closed? Can you make a commit to fix this?

**Comment by pitsi** [comment]
As @crmagicxxx said above, now that all of trakt's... nonsense has stopped*, can we get a fix?

* https://old.reddit.com/r/Addons4Kodi/comments/jj9g41/trakt_api_changes_likely_a_big_impact_to_kodi/

**Comment by elgatito** [comment]
@pitsi what fix you expect? 0.1.59 already had new trakt key which is disabled again.

**Comment by shmizan** [comment]
@pitsi use your own api key, as described in the comments above.
it eliminates the problem, and is not hard to do at all..

**Comment by pitsi** [comment]
@elgatito + @shmizan 
I just got the update to 0.1.59 and the problem is still there. The key was disabled indeed :( 
I do not want to create a trakt account for just the key. As I have said before, I do not create accounts here and there for stuff that should work with much less hassle.

**Comment by antonsoroko** [comment]
@pitsi 
Then simply add support of 429 HTTP status code to elementum code, then maybe shared trakt key will have less probability to be banned.

**Comment by elgatito** [comment]
@antonsoroko nobody notified about the reason why key was disabled. They don't even notify when they disable it.

**Comment by pitsi** [comment]
What if there is something "faulty" in elementum's code that gets the keys to be disabled in such a short time? E.g too many requests.

**Comment by jffp1101** [comment]
Trakt is now enforcing rate limiting for all API's. If Elementum is used a single account in Trakt and all of us is using elementum, of-course others may experiencing issue. But... As I have post above the steps... IT RESOLVED my issue and everything works fine for me! Good luck to all and cheers!

**Comment by elgatito** [comment]
@jffp1101 Rate limiting is applied PER IP, not per Client ID.

@pitsi Trakt support wrote that they disabled elementum Client key because they think it sends too much "set watched" requests. That is a known issue and still is not resolved why it happens.

The only way is to create own keys or wait if Trakt issues in Elementum got fixed some time.

**Comment by pitsi** [comment]
Semi-offtopic.
To be honest with everyone, I am fed up with all that "create an account to access our api" trend that every site wants to enforce lately. I do not want to be tracked, period.
Since mid 2017 I had one single api to bug me with this nonsense, youtube's. I had created my own api keys because there wasno other way to keep using kodis' addon.
Then, in late March 2020, opensubtitles decided to block anonymous access to their api and asked me to do the same.
After that, in early June, youtube decided to do some changes in their api, half the requests per day and delete a lot of api keys, including mine. And now trakt decides to do the same with their api.

**Comment by rudf0rd** [comment]
> What if there is something "faulty" in elementum's code that gets the keys to be disabled in such a short time? E.g too many requests.

So what @pitsi said was correct.  We were seeing a massive influx of duplicate history counts.  For those that don't care about tracking, no big deal, but it will slow your system damn and waste a lot of your bandwidth if you're constantly syncing with Trakt and adding tens of thousands of plays **per day**.  This combined with other Elementum users was impacting performance across all users.

@pitsi As far as why we 're starting to limit is because we've seen developers not treat the API with respect for the rest of the community.  We don't believe this is malicious by any means, but really an indifference to the community.  In order to restore performance, we're going to start putting automated checks in to keep things from blowing up.  Aka spending more time and money policing people.  It's not fun for us either..

To those that have added your own API key, but you're still using broken code from Elementum, in the eventuality this happens with your plugin, we will end up flattening your account to one play, revoking the API key that you created and you'll be back to the same issue.

@elgatito The real solution is to fix the code that is spamming our API.

**Comment by elgatito** [comment]
Please, read the announcement at https://github.com/elgatito/plugin.video.elementum/issues/636
And, please, do not add custom keys, and do not use previous versions of Elementum with Trakt sync.

**Comment by pitsi** [comment]
Please pin that issue report so as to stay on top!
