### ISSUE TITLE
[Bug] Internal Server Error - Trakt->TV Shows->My Progress doesn't open

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#643]
## Steps to Reproduce (for bugs)
1. Go to TV Shows
2. Go to TraktT -> My Progress
3. Internal Server Error notification and it doesn't open it.
* Just to mention: TV Shows - My Collection also get this "Internal Server Error" sometimes but it is still working fine and open it,  also Movies - My Collection is working fine without this error. So basically Trakt is working.

Kodi Debug Log:
https://paste.ubuntu.com/p/sP2bbCws5Y

Is there any connection to this issue?
https://github.com/elgatito/plugin.video.elementum/issues/636

## Your Environment
Elementum 0.1.61
Kodi 17.6
Win 10, 64 bit

**Comment by i6jm** [comment]
same problem

**Comment by marlop352** [comment]
this sounds to me like elementum's API key got revoked again as beyond that I'm getting a 403 error when I try to re-authorize the user or authorize a new one

**Comment by burekas7** [comment]
@marlop352 
I don't have any issue with the authorize process. After updating to 0.1.61 it asked to re-authorize, I did it and everything is ok.

But if this is another issue and not about this "Internal Server Error" please open a new issue.
I don't want it to mix up.
Thanks.

**Comment by marlop352** [comment]
@burekas7 
I also had authorized properly after the update, I just tested the authorize button because I had the same error as you "Internal Server Error" when trying to load the My Progress page and changing the keys fixed both errors.
If you try the authorize button right now it is still working? If it is I will open a new issue for the 403 error.
Otherwise if you receive the 403 error than this is the same bug and I'm almost sure that it indeed is.

**Comment by elgatito** [comment]
@burekas7 API key is disabled by Trakt, v0.1.62 uses new key, so please re-authorize in Trakt.
The issue, described here, should be fixed in 0.1.62.

**Comment by burekas7** [comment]
@elgatito 

Thanks.
Install 0.1.62 + re-authorize fix the problem.
