### ISSUE TITLE
[Request] Movies and tv shows studios info, number of episodes per season

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#684]
Is there a possibility to insert information about movie and tv show studios into metadata (Universal, WB, Netflix...)? It appears to me in some movies, some of them are missing. For the tv shows, I don't get information about which studio it is or for rarely tv shows appears.
And the second thing, there is a possibility to insert data how many episodes contains each season? Let's say it is in some scrapers and in tmdb helper. Is it perhaps possible to fit in the elementum as well? Thanks in advance.

**Comment by elgatito** [comment]
@matke-84 If you know any movie/show that has information on TMDB website, that you don't see in Kodi - send examples.

**Comment by matke-84** [comment]
@elgatito Studio logo missing in almost all TV shows and some movies. As for the number of seasons and episodes, that is nowhere to be found. Here is an example of Game of Thrones.
![IMG_20210212_191540](https://user-images.githubusercontent.com/74268331/107806176-c4284f80-6d66-11eb-913c-2d34386fdf5e.jpg)
![IMG_20210212_191519](https://user-images.githubusercontent.com/74268331/107806199-cc808a80-6d66-11eb-9d97-f82cb0de896f.jpg)

**Comment by matke-84** [comment]
@elgatito Can you please fix at least the studio logos. Somewhere they appear, somewhere they don't appear. It's little annoying. For example I don't have that problem with tmdb helper. I get every single studio logo for movie or tv show. Thanks in advance.

**Comment by Bequiet19** [comment]
I have the same problem. For some movies and tv shows I have studio information for some not. If I turn on option in elementum to pull trakt information then I get all studios for all movies and tv shows but I can't use this option because I don't have fanarts then. Obviously, a small thing is a problem that only @elgatito can solve. I don't understand programming so I can't fix this.

**Comment by elgatito** [comment]
I do not know any way to specify studio icons to Kodi (and where to get them). 
I guess it's a custom functionality of a specific skin, which reads 'studio' field and try to find an icon somewhere.

If anyone has a solution - feel free to give an advice.

**Comment by matke-84** [comment]
@elgatito I tried what @Bequiet19 said to turn on option in elementum to pull trakt information and studio icons really do appear for all movies and tv shows. You could also take a look at how this works in tmdb helper. With tmdb helper I also get all studio icons. I also thought it was up to my skin, but the same thing happens with all the skins I’ve tried. Since I am working on the development of one popular skin, I know that a skin helper service is necessary for showing studio icons. Maybe it will mean something to you if you want to test elementum with some skin.

**Comment by elgatito** [comment]
@matke-84 I do not see any studio icons in Estuary skin, in any addon.
Here is the list of labels in Kodi: https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14

**Comment by matke-84** [comment]
@elgatito Wow. You managed to set up a studio logo. Thank you very much. 👍
Please tell me if there is a chance to set up elementum to provide information about number of seasons and episodes for TV shows? The skin I'm developing with a few other people has that capability and with local scrapers and tmdb helper I get that information but I don't have it with elementum.

**Comment by elgatito** [comment]
@matke-84 what, exactly, you need for episodes/seasons?

**Comment by matke-84** [comment]
@elgatito Total seasons and total episodes per seasons. It was used in the skin as follows:
![IMG_20210405_220313](https://user-images.githubusercontent.com/74268331/113621030-683dc100-965b-11eb-926b-54fedf428916.png)
![Screenshot_20210405_221454](https://user-images.githubusercontent.com/74268331/113621839-72ac8a80-965c-11eb-97b1-285fea54b137.png)

**Comment by matke-84** [comment]
@elgatito @antonsoroko One question. Can it be set to display network logo in tv shows instead of production studio logo. For example, The Simpsons, instead of Gracie Films to show Fox.

**Comment by matke-84** [comment]
@elgatito I think elementum has something to do with it. Tmdb helper, for example, provides information for a TV show network. Yes, the skin helper service is in charge of this in my skin (Titan bingie mod) but it takes the information that elementum sends. If the elementum sends information about the studio instead of the network, it will display the studio logo. It's not a problem, it can stay like this, I just asked. Until recently, elementum did not even display the studio/network logo. But thanks to you, we have that now. 🙂

**Comment by antonsoroko** [comment]
@matke-84 

so in order to try add these i would like to know how (from where) you take info to:

1. show total count of episodes in season
2. show total count of episodes in show
3. show unwatched count of episodes in show
4. show video progress percentage
5. for logos - i think that skins are in charge to tell kodi which logo kodi should provide them. otherwise people would not be able to choose what to show as logo. if you know how skins do that (or kodi, or else) - then we can try to do something about that. 

maybe you use some infolabels from https://kodi.wiki/view/InfoLabels#ListItem
but i do not see anything that would match on this page, so i want to see how you get that info.

as i can see appropriate code should be in skin's xml files.

**Comment by antonsoroko** [comment]
@matke-84 

i did some easy changes - number of seasons/episodes and setting to choose network or production studio.
probably i will not to do more sophisticated things like `ListItem.Property(WatchedEpisodes)` and `ListItem.Property(UnWatchedEpisodes)` since it will take more time than i am ready to spend on this feature. but feel free to open new feature request for these things.

please test:
[elementum.zip](https://github.com/elgatito/plugin.video.elementum/files/6626907/elementum.zip)
https://github.com/antonsoroko/plugin.video.elementum/archive/refs/heads/enhancements-for-skins.zip

**Comment by antonsoroko** [comment]
examples:

![Screenshot_Kodi_20210610_000212](https://user-images.githubusercontent.com/17964763/121430183-76bc9780-c980-11eb-8b85-0d21d5a84b86.png)

![Screenshot_Kodi_20210610_000234](https://user-images.githubusercontent.com/17964763/121430177-74f2d400-c980-11eb-8bfc-833916bdfd5f.png)

**Comment by matke-84** [comment]
@antonsoroko I'm sorry, I didn't get to answer you earlier. I have a lot of work.
I didn't get to test in detail but the number of seasons and episodes per season works nice as I can see. :-) Studio logo and the network logo it also works nicely. :-) I only noticed when I turn off the option you inserted to switch between the production studio and network, it doesn't work properly. Actually then I don’t get a production studio logo for every tv show. It was a problem that existed before @elgatito fixed it. But when the option is turned on it works as it should. Maybe even not need this option but if you want to keep it you need to know it has this problem. I am happy with this you make the network work properly. :-)
As for the answers to your questions, I am not able to answer you in detail now, but everything important is in this file. 
https://github.com/AchillesPunks/skin.titan.bingie.mod/blob/matrix/xml/IncludesBingie.xml
I haven't done this skin from the beginning, I got involved in its development a few months ago. I'll try to find you what you're looking for later. Skin also uses additional addons such as skin helper service, metadatautils...  For example, as far as I know, metadatautils is in charge of the studio logo in skin.

**Comment by antonsoroko** [comment]
@matke-84 
1. 
> Actually then I don’t get a production studio logo for every tv show. 

i do get them
![image](https://user-images.githubusercontent.com/17964763/121497283-f3349200-c9e3-11eb-97f6-764abe9d213f.png)

please note that all these will properly work only with tmdb as source in elementum (you also can use trakt, but trakt does not give you prod companies and number of seasons are not available out of the box, only number of episodes)

before my change elementum received `production_companies` and `networks` from tmdb (see https://developers.themoviedb.org/3/tv/get-tv-details ) then combined them and set as `ListItem.Studio`

now it either  `production_companies` or `networks`.

The only thing is when video has multiple companies/networks - skin will show text instead of logo because
`2021-06-10 12:14:04.026 T:1185134   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/NBC / FOX.png`

Also unlike networks - prod companies often don't have logo in kodi - https://github.com/XBMC-Addons/resource.images.studios.white/tree/master/resources

e.g. `2021-06-10 12:22:00.978 T:1194926   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/CBS Television Studios.png

this is true at least for skin.aeon.nox.silvo

maybe it makes sense to provide not all "studios" but only first one. i dunno.

2. >https://github.com/AchillesPunks/skin.titan.bingie.mod/blob/matrix/xml/IncludesBingie.xml

    that's a lot of text :-) okay, if we will have some issues, then we can try to read it.

**Comment by matke-84** [comment]
@antonsoroko 
It gives me information for seasons and episodes for both in trakt and tmdb at least what I saw.
Yes, you are right. You actually get information about the studio or network, but if there is no image, the skin will not show it. In fact elementum before used it to mix network and studio, so if there is no one, you get the other and that was ok too but now I will definitely use network for the tv shows because it makes sense to me for tv shows. This second option with the production studio is only interesting if something would be combined again because in this way it remains empty space in skins like mine. If we keep this function I would just move it to appearance tab.
**No studio**
![no studio](https://user-images.githubusercontent.com/74268331/121504203-1c542300-c9e2-11eb-87df-350deac2931c.png)
**With sudio**
![with studio](https://user-images.githubusercontent.com/74268331/121504218-1f4f1380-c9e2-11eb-9df4-7dc245090047.png)
Yes, there is a lot of text. :-) I'll see if I can send it to you for:
3.show unwatched count of episodes in show
4.show video progress percentage
We don't need for rest now or maybe we need it? :-)

**Comment by antonsoroko** [comment]
i see. but this is issue of the skin to be honest. standard skin shows everything. your skin also can do that.

>I would just move it to appearance tab.
will do.

3. my guess is that skins either calculate it by subtracting `ListItem.Property(WatchedEpisodes)` from `ListItem.Property(TotalEpisodes)` or by using `ListItem.Property(UnWatchedEpisodes)` if available
4. my guess is `ListItem.PercentPlayed`

but please check.

**Comment by matke-84** [comment]
@antonsoroko No no. I agree with everything. In your skin, it displays text instead of a logo it can't find. It's OK. In my skin, it works like I said, an additional addon, metadatautil, probably in a different way. It is enough for me to show me the network for the tv shows. :-) The movies have worked fine so far. Can you just tell me if it shows you the logo for Star Wars Rouge One od Star Wars The Last Jedi? That's where I noticed I didn't have a logo.

You're all right. :-) I'm sending you just to see what some lines of code look like.
For total seasons:
https://github.com/AchillesPunks/skin.titan.bingie.mod/blob/c9bc2d988161997b5708429ec75a0142cba7f4c2/xml/IncludesBingie.xml#L879
Watched info:
https://github.com/AchillesPunks/skin.titan.bingie.mod/blob/c9bc2d988161997b5708429ec75a0142cba7f4c2/xml/IncludesBingie.xml#L2692
Percent played:
https://github.com/AchillesPunks/skin.titan.bingie.mod/blob/c9bc2d988161997b5708429ec75a0142cba7f4c2/xml/IncludesBingie.xml#L3232

**Comment by antonsoroko** [comment]
1. yes, for both. because they have only 1 prod company (there is no network for movies in tmdb, which i guess is correct). but for movies that has more than 1 company - i get them as text. 
  as i said
  >maybe it makes sense to provide not all "studios" but only first one. i dunno.

2.  okay, all these 3 things are not quick to implement, so i will not do this now. but i created a issues for them.

**Comment by matke-84** [comment]
@antonsoroko 
1. Forget this. :-) Star Wars logo works with white logo. There is probably some problem with color logo. It doesn't matter so much.
2. Ok. Sounds good. I am here for every kind of help. If you need something to test feel free to contact me. ;-)
