### ISSUE TITLE
(Request) Manage artwork option

### ISSUE THREAD

**Issue by Bequiet19** [elgatito/plugin.video.elementum#738]
I found one great option in tmdb helper. Manage artwork! With this option, any artwork can be changed. @elgatito With this option you would solve the problem with frequent questions I want this artwork, I want that... I saw that there were a lot of questions like this. On the other hand, there is a lot of space for customization, who likes that. I use artic horizon skin with tmdb helper and it looks great. But I also love so much elementum. So please add this option. Pleeeease. :-)

**Comment by matke-84** [comment]
@antonsoroko 
To not open a new topic when it already exists and we talked about this. What are the chances of implementing of this?

**Comment by antonsoroko** [comment]
i am not interested in this since i do not use library and i do not care about artworks in general. sorry.
and this is probably quite hard/tedious to implement.
so if it will be implemented then probably not by me.

**Comment by matke-84** [comment]
@antonsoroko 
Fair enough.

**Comment by antonsoroko** [comment]
@matke-84 @Bequiet19 

so, i took a look into this and i do not see the big issue here.

in skin you can click "information" and then "choose art" and them you will be able to choose different images.
of course if you use only tmdb - the images selection is small.

but if you set "Use Fanart.tv for posters/images" option in elementum - then you have enough of choices.

example:

![image](https://user-images.githubusercontent.com/17964763/121548556-c7ca9b00-ca15-11eb-9106-6abd55ae228d.png)


on the other hand - looks like official tmdb scraper adds more images of every art type, e.g. we have only a lot of fanarts but not other types of arts.

this is because we use `setArt()` func
https://github.com/elgatito/plugin.video.elementum/blob/master/resources/site-packages/elementum/navigation.py#L442
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#gad3f9b9befa5f3d2f4683f9957264dbbe
that was added in kodi 13

while new tmdb scraper uses `addAvailableArtwork()` func
https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/addons/metadata.themoviedb.org.python/python/scraper.py#L81
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga029e2e45023ed17a8f5305249959a149
that was added in kodi 18


so if by "manage artworks" you mean just to have more images - then it can be done.
changing of image in UI is of course will be by kodi/skin as i described above.

**Comment by antonsoroko** [comment]
@matke-84 
>This also works with the online database in TMDB helper,

did you mean that TMDB helper can change artwork for elemetum items? or something else?

also - what is the full name (or better addon id) of this "TMDB helper" addon?

**Comment by matke-84** [comment]
@antonsoroko Unfortunately no. Works only with tmdb helper. That's his menu. 
TheMovieDB Helper. Here is the link.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper
I found it while the elementum had stopped developing a bit. Besides the elementum the only addon I still use but lately much less often.

**Comment by antonsoroko** [comment]
@matke-84 
so i tried to read their code and search info about this in kodi.
looks like there is no way to use internal kodi functionality to change artwork for non-library items.
and in addon code i can see that they use custom dialogs to ask user about what to change and to what image.

could you please confirm that tmdb helper does not use kodi internal functionality and use its own dialogs?

**Comment by matke-84** [comment]
@antonsoroko Yes, I confirm that tmdb helper is not using Kodi internal artwork manager but his own. When I use the internal kodi artwork manager then the same thing happens as the elementum, only temporarily change image and then immediately returns to the default. When I use tmdb helper artwork manager then the image is saved.
![artwork1](https://user-images.githubusercontent.com/74268331/122120744-18356480-ce2b-11eb-8f5e-7da2dd399b39.png)
![artwork2](https://user-images.githubusercontent.com/74268331/122120762-1b305500-ce2b-11eb-9d0c-f6379a2d4206.png)
![artwork3](https://user-images.githubusercontent.com/74268331/122120767-1d92af00-ce2b-11eb-8741-b80534f88242.png)
![artwork4](https://user-images.githubusercontent.com/74268331/122120772-1ec3dc00-ce2b-11eb-9aac-dfac56311fbc.png)

**Comment by antonsoroko** [comment]
thank you for screenshots!

yeah, so basically they re-implemented existing kodi functionality because it does not work with non-library items.
to be honest it should not be super hard to do the same but i would prefer to do something more relevant for me at the moment.

in case if someone is interested - here is the "reference" code from thdm helper - https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/abc6e8bb6284571a90d95cb2e228bec2a106b5cd/resources/lib/fanarttv/api.py#L232

but ideally, I would prefer that kodi introduce some sort of mechanism to notify addons that an image has been changed by the user.

**Comment by matke-84** [comment]
@antonsoroko You're welcome. Thank you for everything you do. ;-)
