### ISSUE TITLE
[FeatureRequest] Display episodes aired today

### ISSUE THREAD

**Issue by Virusmater** [elgatito/plugin.video.elementum#743]
As far as I understand from the code
```	now := util.UTCBod()
		if config.Get().ShowUnairedEpisodes == false {
			if episode.AirDate == "" {
				continue
			}
			firstAired, _ := time.Parse("2006-01-02", episode.AirDate)
			if firstAired.After(now) || firstAired.Equal(now) {
				continue
			}
		}
```
Elementum gets the current date in UTC (and the time is always 00:00), then tries to convert the air date to UTC as well (without a TimeZone and the time is always 00:00).
This leads to the problem like it isn't possible to watch the episode on the air date and a little bit on the next day (given I live in UTC +2 I can see the episode only after 2am the next day).
Release groups are working really fast nowadays, especially when series are released on the streaming service first.
So would it be possible to add an additional configuration where a user could avoid  "firstAired.Equal(now)" comparison?
Or maybe instead of UTC use system's timezone everywhere.

**Comment by antonsoroko** [comment]
Hi @Virusmater 

I don't think that this code is causing your issue.
I read the code and this is what i can see (unless i missed something):

1. about time - https://golang.org/pkg/time/
a. `Now returns the current local time.`
b. `UTC returns t with the location set to UTC.`

So it will just "standardize" your local time. And then as you noticed, elementum will strip out time from it to get a "standardize" date.
https://github.com/elgatito/elementum/blob/46204e32f7923dad475adc8c7347cb08769f184e/util/time.go#L29-L32

you can run this snippet on your machine to test this "standardization" https://play.golang.org/p/PaPYxkQAbS4

2. Depending on your settings (i mean `Use Trakt information in Trakt lists` option) elementum will use tmdb (default) or trakt for air dates.

a. tmdb uses only date and this date looks like a local date for the show's origin country (e.g. for USA show it will use air date for USA time zone). So no UTC there - meaning that date is not "standardize".
for some cases this might lead to a confusion because you might perceive that episode was released yesterday (for your time zone) when it was actually released today or even just will be released today (b/c their time zone is far behind).
on a separate note: for things like anime that are released in a country which TZ is far ahead of your TZ you will see date in future, which maybe is your case.

b. trakt uses already normalized time - i mean converted to UTC. and then elementum strip out time of it.
on a web site trakt uses your TZ (e.g. adds some hours to this UTC time). So you will see real release time for your TZ.

Important note: elementum does not do any time conversion here (and as i mentioned tmbd, for instance, does not provide time at all). It just take provided date and set time to 00:00 UTC (so it can compare 2 days w/o TZ tricks).

This basically means that elementum compares start of the day of the release with start of the user's day.
For USA show and with source of info set to
a. tmdb - for TZ that is far ahead of USA TZ it will actually give you episodes that are not released yet about a day before.
b. trakt - will give you episodes only a few hours before they was really released.

as an example:
reference date - https://www.adultswim.com/videos/final-space/change-is-gonna-come
`Saturdays at 10:30p` (USA time)
e.g. April 24 2021 22:30.

https://trakt.tv/shows/final-space/seasons/3/episodes/6
`$ curl -H @trakt-headers.txt https://api.trakt.tv/shows/final-space/seasons/3?extended=full`
`"first_aired": "2021-04-25T03:30:00.000Z",` <--- they added 5h difference with UTC

so if your TZ is UTC+2 and your date is 25th and your time is more than 02:00 - elementum will compare 25 with 25 and will give you episode. this is quite correct behaviour. the only thing is that episode will be released only at 05:30 your time.

https://www.themoviedb.org/tv/74387-final-space/season/3/episode/6
`$ curl -s https://api.themoviedb.org/3/tv/74387/season/3/episode/6?api_key=xxx`
`"air_date": "2021-04-24",` <--- they just use date

so if your TZ is UTC+2 and your date is 24th and your time is more than 02:00 - elementum will compare 24 with 24 and will give you episode. this is kind of correct behaviour. the drawback is that episode will be released only on 25th at 05:30 your time.

But anyway, this means that for USA tv shows, for instance, in elementum you will always see episodes before they actually were released.

So if you are talking about USA shows, then my guess is that either you ran into situation when tmdb/trakt has wrong release date (or episode was leaked) or when release date was changed and your local cache still has old (later) date:

https://github.com/elgatito/elementum/blob/4cfb76705389bbda44af657a76524fa6071a0e2f/cache/types.go#L40
https://github.com/elgatito/elementum/blob/4cfb76705389bbda44af657a76524fa6071a0e2f/cache/types.go#L8

If you are talking about  Asia-Pacific shows, then if episode was released in their morning (so for you it will be evening of the previous day) - then yes, with tmdb you will have to wait for a new day in terms of UTC (02:00 for you) because tmdb does not have time and has a "local" date (i am not sure about local date - it just looks like it. i checked on some popular anime show but  i suggest you to check it for your show).

Since we can't do anything about tmdb - **solution** for you will be to use info from trakt - enable `Use Trakt information in Trakt lists` option. Since thakt uses UTC time - elemetum can properly understand the release day. In this case you will see episodes slightly before they actually were released (because we remove time).

As a side note: another notable option here is to "show unaired episodes" which can help with leaked episodes (it smart enough so it will not affect "my progress", only list of episodes inside season).


@elgatito knows more and can correct me if i am wrong.

---
Anyway, If you can provide real example (with links to tmdb/trakt/offcial release time) then it will be easier to understand why it happens to you.

**Comment by elgatito** [comment]
@Virusmater There is nothing to change in the code. You can disable option to hide unaired episodes.
TMDB does not store time or release, only day. That means that in 1AM you will see all the items for that day. 
That is why we check if `now` is the next day after release date.

**Comment by Virusmater** [comment]
Just an example that will work only now and today:
https://trakt.tv/shows/the-handmaid-s-tale/seasons/4/episodes/1
Elementum hides that episode in my timezone (CET) right now, but according to trakt it was released "April 28, 2021 9:00 AM"
I tried both with and without "Use Trakt information in Trakt lists" option.

My problem that I see items only the next day after 2AM, not the same day after 2AM.

Will come back with an output of golang snippet on my machine.

**Comment by elgatito** [comment]
@Virusmater Elementum is using TMDB for that information, not Trakt.

**Comment by Virusmater** [comment]
I understand the problem with TMDB has no information about timezone, so Elementum treats Air Date (firstAired) as 28-04-2021 00:00:00 UTC and current datetime (now) as 28-04-2021 00:00:00 UTC.

But I find it really strange when current date is 28-04-2021, Kodi shows air date as 28-04-2021, everywhere around the globe now 28-04-2021 or 29-04-2021 already, but Elementum still hides the season/episode.

I still don't understand why 
>  we check if now is the next day after release date.
wouldn't it be better to check if now (in UTC) is the day of the release or after (in UTC)?

**Comment by Virusmater** [comment]
Even if we will take an ideal situation when the user lives in UTC timezone and the episode was aired at the midnight of UTC timezone - the user still will not see the aired episode on the same day. The user will have to wait till the next day because `firstAired.Equal(now)` will return true.

In case of Episodes released in Japan see even bigger problem:
Let's say right now:
- My time right now: 22:30 28 April 2021 (CEST)
- Episode was just released in Japan: 05:30 29 April 2021 (GMT+9)
- Elementum translates my current time (now) to 00:00 28 April 2021 (UTC)
- Elementum translates air date (firstAired) to 00:00 29 April 2021 (UTC)
- Elementum checks if the episode should be showed `if firstAired.After(now) || firstAired.Equal(now)`
- `firstAired.After(now) == True`

That means that Elementum doesn't show the Episode as aired yet. Okay, not much we can do there, let's wait till tomorrow

Then tomorrow:
- My time tomorrow: 22:30 29 April 2021 (CEST)
- Episode was released already more than 24 hour ago in Japan: 05:30 29 April 2021 (GMT+9)
- Elementum translates my current time (now) to 00:00 29 April 2021 (UTC)
- Elementum translates air date (firstAired) to 00:00 29 April 2021 (UTC)
- Elementum checks if the episode should be showed `if firstAired.After(now) || firstAired.Equal(now)`
- `firstAired.After(now) == False`
- `firstAired.Equal(now) == True`

That means that Elementum still doesn't show the episode that was aired more than 24 hours ago. Isn't it an issue?

Is my logic is wrong somewhere?

In my situation I would rather see that an episode was aired today, but no torrents are available than no episodes are available at all.
That's why I was saying about the configurable option in Elementum.

**Comment by antonsoroko** [comment]
so i missed that `aired.Equal(now)` will trigger continue/return depending on the case.

maybe we really should remove `aired.Equal(now)`?

also for "my progress" "Use Trakt information in Trakt lists"  will be used. and at least for "user lists". but look like it is not used for just browsing trakt.
anyway with `aired.Equal(now)` even trakt also will not work for Asian-Pacific.

as a temporary solution - for "my progress" there is "Hide unaired episodes" setting and for browsing - "show unaired episodes".

**Comment by antonsoroko** [comment]
i mean it works for majority of people because they watch USA tv shows and they usually released in the evening, so for us it a next day and tmdb gives the previous day. but if USA show will be released in the morning - we also will not see it on the same day, since for us it also will be the same day and `aired.Equal(now)` will screw the logic.

**Comment by Virusmater** [comment]
I'm using an integration with Kodi library and don't really use Trakt. If I will check `"Show unaired episodes"` - then they all will be immediately added to the library and there is no notification or way to know right away when an actual episode will be aired.

> we can just introduce the logic that will suppress aired.Equal(now) or we can remove it completely.

either of those will work for me beautifully for me.

actually I'm really surprised that this issue wasn't discussed before.

**Comment by antonsoroko** [comment]
>actually I'm really surprised that this issue wasn't discussed before.

i think that
>it works for majority of people because they watch USA tv shows and they usually released in the evening

and i guess that only not very popular Japan's show air in the morning (since the morning is not a time for something popular in general :-) )

so i think current logic works for the majority of the people. and other people probably just ignore this issue :-|

**Comment by Virusmater** [comment]
Just decided to check if that logic really works for majority of people living in Europe based on most popular series right now (based on trakt trending).
Current logic works okay with (released late evening in USA and TMDB will show it as yesterday):

- The Curse of Oak Island
- Supergirl
- New Amsterdam
- The Blacklist

Current logic will show the episode only the next day (released early morning in USA):

- The Handmaid's Tale
- Shadow and Bone
- For All Mankind
- Line of Duty
- The Falcon and the Winter Soldier

So yeah, I would rather see those episodes added a bit early to Kodi library than not see them at all and have to go to the torrent search manually. I'm all in to make it configurable or remove `aired.Equal(now)` for everybody.

**Comment by elgatito** [comment]
If I remember correctly, TMDB does NOT have timezones within air dates. 
TMDB is filled by people, who just write in a date in a text field.
That means you get same air date for shows from Japan / US / UK. 
And same date, no matter where you live.

Elementum is checking to avoid showing Today premieres. If you want to bypass that check - enable in settings to show unaired episodes.

**Comment by Virusmater** [comment]
> If I remember correctly, TMDB does NOT have timezones within air dates.
> TMDB is filled by people, who just write in a date in a text field.
> That means you get same air date for shows from Japan / US / UK.
> And same date, no matter where you live.

I fully understand it.

the part I don't understand is why

> Elementum is checking to avoid showing Today premieres

I don't want to see all unaired episodes, but I want to see episodes that were aired today. And, if possible, to do it configurable. If the team is strongly against it for some reason - that's fine, you can close this issue.

**Comment by antonsoroko** [comment]
I think we can do this as a configurable option, that is disabled by default.
"Hide unaired episodes" and "Show unaired episodes" are useful when you need to see leaked episodes, but for this case - not really, since it will "clutter up" your progress, for example.
