### ISSUE TITLE
Bugs with new elementum 0.1.79

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#795]
@antonsoroko @elgatito Hi guys. first I would like to thank you for all the implementations in this update. But unfortunately some things don’t work properly. So let's start.
1. The biggest problem of all is that now I can't play a movie or enter a tv shows from the widget.
Movies
![movies](https://user-images.githubusercontent.com/74268331/122713650-4de0b000-d266-11eb-87f9-07fd4fdf0870.png)
TV Shows
![tv shows](https://user-images.githubusercontent.com/74268331/122713677-55a05480-d266-11eb-95f4-7b5933c3a4c3.png)
2. Also, when I enter moreinfo, it throws me the error that the cast button has a problem, it just doesn't appear in this section anymore.
Cast button missing
![cast missing](https://user-images.githubusercontent.com/74268331/122713813-8ed8c480-d266-11eb-8e7b-81733da62382.png)
3. I saw that the implemented function choose artwork. Do I need to adjust something special since I don't get any artwork except posters and fanart.
Choose artwork
![artwork](https://user-images.githubusercontent.com/74268331/122717739-550abc80-d26c-11eb-9a8d-8041915b2b4c.png)
4. Also the function mark as  watched in trakt from elementum context menu doesn't work. It constantly throws out a mistake. The option outside from elementum context menu works.
Mark as  watched
![mark as watched](https://user-images.githubusercontent.com/74268331/122718250-ff82df80-d26c-11eb-935e-55e0d2e2e198.png)
5. Show number of unwatched episodes in shows/season option works and it is very useful but the first loading of each page is terribly slow, it is almost unusable. I know it processes a lot of information but I didn't think it would be this slow.
6. The show more info option for tv shows no longer works.
![more info](https://user-images.githubusercontent.com/74268331/122723320-20e6ca00-d273-11eb-9ea8-5c4904b151cb.png)
Log
https://paste.kodi.tv/azolimopiv.kodi
I hope you can handle these things since elmentum is useless for me now. I'm going back to 0.1.78.

**Comment by antonsoroko** [comment]
@matke-84 hi.
looks like you do not have **debug** enabled in elementum so i do not see some info.
also it is better to use **1 log file per 1 problem**, otherwise it is hard to trace the particular problem in 1 big log file.

1. i do not see error in log but i think it is #793 that will be fixed by #794 . see that issue for intermediate fix.
2. +6. these 2 came up because of the hack i used to make kodi manage artworks for non-library items - if item in library - then we use real kodi library id and everything is legit, otherwise we generate fake id. i expected that it will break some addons that rely on info from kodi lib, but also i just did not expect that people will use such addons on items that are not from library.
in your case the issue is caused by `script.skin.helper.service` and `script.module.metadatautils` - you can see their errors in log.
they invoke kodi lib api requests `'method': 'VideoLibrary.GetTvShowDetails', 'params': {'tvshowid': 1000001399,` and `'method': 'VideoLibrary.GetMovieDetails', 'params': {'movieid': 1000293660,` on fake items and they fail.
i guess before they simply did not show you info since there were no kodi id for elementum items. **is this assumption correct?**
anyway, i think i will disable it by default and mark as "use at your own risk".

3. for more artworks - fanart.tv should be enabled. but i see it is enabled in your log, but i also do not see any errors and it works for me. either it is skin issue or caused by issues described above. **do you use this feature on elementum or kodi library item?** (if elementum - is this item also added to library?)
4. in general, context menu addon is supposed to be used on kodi library items only, with some exceptions like "assign torrent". "mark as watched" in context addon only for kodi lib. for elementum - internal menu. it will be hidden by https://github.com/elgatito/context.elementum/pull/22 
5. with tmdb as a info source it is not super slow - try to use "trakt as a info source" to see real slow :-) anyway - when list has many shows and vast majority of these show are not watched by you - it will take a lot of time, since we check every episode against our internal database with playcounts. that's why it is disabled by default. maybe i will be able to fix it, otherwise - "use at your own risk" again.

**Comment by matke-84** [comment]
@antonsoroko 
1. Sorry, I completely forgot to turn on debug in the elementum. If you can send me a test version before you release the update. 
2. With version 0.1.78 this information worked perfectly. I also received info about the actors and complete information about the tv shows. I didn't have this bug with version 0.1.78.
3. I don't use the local library at all. Elementum only. I don't put what I watch in the library. I watch streaming directly. And it has nothing to do with skin. Kodi installation is fresh.
![artwork2](https://user-images.githubusercontent.com/74268331/122753068-ffe1a180-d291-11eb-8aa9-05e144efe704.png)
4. OK. I didn't know that. In that case, I will not be able to use it in widgets, but only directly in elementum.
5. Yes, I know about the trakt. :-) It would be great to speed it up a bit. You will agree with me that it is a good function but if it will reflect on speed then it is not worth it.

**Comment by matke-84** [comment]
@antonsoroko One very important thing. All the skins that use skin helper service, metadatautils... have these bugs that I have with my skin ... There are a lot of such skins.

**Comment by antonsoroko** [comment]
@matke-84 
1. just as a note - debug should be enabled in both kodi and elementum http://elementum.surge.sh/contribute/log/
2. i see. in this case my hack to make "choose art" work will not work for you since you will loose info-related things you described. in standard skins - everything is ok since they do not use these addons i mentioned before. (as we already discussed it will take some extra effort to make our own "manage artworks" UI and nobody wants to do that. that why we ended up with a hack - but this hack works perfectly with items that added to the library and only mess up things with items that are not in lib.)
3. strange. works for me. maybe make a fresh log file with debug enabled and only with this action (choose art).
4. you actually could if you would use library integration. then if movie/episode in library - menu would appear even for widget. for "pure" elemetum videos - menu would be only inside elemetum. it could be changed to support also non-library items - but it will take extra effort for very minimal profit - so maybe later. i think we already discussed that in relevant issue.

**Comment by matke-84** [comment]
@antonsoroko 
2. I need to see if something can be done with the skin helper service and metadatautils. This ability to change artwork is great to me. :-)
3. https://paste.kodi.tv/yupoduganu.kodi
4. Ok.

**Comment by matke-84** [comment]
@antonsoroko 
3. Figured out that I can add artwork myself. (clearlogo, clearart...) :-) I love this option. We have to somehow make work in skin without these bugs. :-)

**Comment by antonsoroko** [comment]
2. you can set up kodi library - so artworks will work at least for things that you will add to library (without issues with skin). but yes, this is so-so approach. i do not think there is something can be done with these addons, since they works as expected - they see kodi library id and try to use it. but id is fake so they fail. the only right way is either to wait for kodi to add feature that allows video plugins to change art or implement own ui for that.
<details><summary>from your 1st log file</summary>

```2021-06-21 09:20:19.675 T:308     DEBUG <general>: script.module.metadatautils --> {'jsonrpc': '2.0', 'method': 'VideoLibrary.GetMovieDetails', 'params': {'movieid': 1000293660, 'properties': ['dateadded', 'file', 'lastplayed', 'plot', 'title', 'art', 'playcount', 'streamdetails', 'director', 'resume', 'runtime', 'plotoutline', 'sorttitle', 'cast', 'votes', 'showlink', 'top250', 'trailer', 'year', 'country', 'studio', 'set', 'genre', 'mpaa', 'setid', 'rating', 'tag', 'tagline', 'writer', 'originaltitle', 'imdbnumber', 'uniqueid']}, 'id': 1}
2021-06-21 09:20:19.675 T:308   WARNING <general>: Skin Helper Service --> Exception details: Type: KeyError Value: 'cast' Traceback: Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\plugin_content.py", line 67, in main
                                                       getattr(self, action)()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\plugin_content.py", line 266, in getcast
                                                       all_cast = self.mutils.kodidb.movie(db_id)["cast"]
                                                   KeyError: 'cast'                                                   
2021-06-21 09:20:19.675 T:308     ERROR <general>: Skin Helper Service --> Exception in resources.lib.plugin_content ! --> 'cast'
...
2021-06-21 09:20:25.237 T:8272    DEBUG <general>: script.module.metadatautils --> {'jsonrpc': '2.0', 'method': 'VideoLibrary.GetTvShowDetails', 'params': {'tvshowid': 1000001399, 'properties': ['dateadded', 'file', 'lastplayed', 'plot', 'title', 'art', 'playcount', 'sorttitle', 'mpaa', 'premiered', 'year', 'episode', 'watchedepisodes', 'votes', 'rating', 'studio', 'season', 'genre', 'cast', 'episodeguide', 'tag', 'originaltitle', 'imdbnumber']}, 'id': 1}
2021-06-21 09:20:25.238 T:8272  WARNING <general>: Skin Helper Service --> Exception details: Type: KeyError Value: 'season' Traceback: Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\plugin_content.py", line 67, in main
                                                       getattr(self, action)()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\plugin_content.py", line 272, in getcast
                                                       all_cast = self.mutils.kodidb.tvshow(db_id)["cast"]
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\kodidb.py", line 57, in tvshow
                                                       return self.tvshow_watchedcounts(tvshow)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\kodidb.py", line 742, in tvshow_watchedcounts
                                                       tvshow["extraproperties"] = {"totalseasons": str(tvshow["season"]),
                                                   KeyError: 'season'
2021-06-21 09:20:25.238 T:8272    ERROR <general>: Skin Helper Service --> Exception in resources.lib.plugin_content ! --> 'season'
```

</details>

3. good then. what was the issue? (i wanted to ask you to enable "component-specific logging" in logging setting in kodi, and then do "elementum menu..."->"info" to see info about selected video. but i think it is not needed anymore)

**Comment by antonsoroko** [comment]
in my kodi i do not need to add anything manually

![image](https://user-images.githubusercontent.com/17964763/122767261-22cc7f80-d2ab-11eb-9ebe-bbd96574db25.png)

**Comment by matke-84** [comment]
2. I'll see with the guy who maintains these addons if something can be done.
3. When installing clean kodi without local scrapers then each artwork must be entered manually (must be typed in dialog)
![add artwork](https://user-images.githubusercontent.com/74268331/122767292-ca917f80-d2a2-11eb-94f0-d567e8216762.png)

**Comment by antonsoroko** [comment]
3. strange. i did not make such actions on my dev env. all art types were there from the start.

**Comment by matke-84** [comment]
@antonsoroko 
Tested on two different devices (pc and android box). The same thing.

**Comment by antonsoroko** [comment]
lol, i just checked on my android tv - there i also have only poster and fanart. this is not cool, but this is kodi issue imho.

**Comment by antonsoroko** [comment]
2. btw, there is a hack that can be used - check if kodi id is less or equal than 1000000000. we will do this in context - https://github.com/elgatito/context.elementum/pull/22/files . but for 3rd party addons - i guess they will not be happy to add such workaround.

**Comment by elgatito** [comment]
@antonsoroko All that does not make sense to me. I would just remove all that functionality or add customer art selector like they do in tmdb helper. Otherwise the feature is not usable and makes more trouble than help.

**Comment by antonsoroko** [comment]
@elgatito 
we can keep this feature at least for real kodi libary items - there are no issues with them.
but for non-library items - i am not sure how to proceed. i did not expect such issues. maybe it is better to remove fake ids.

**Comment by matke-84** [comment]
@elgatito @antonsoroko I really like this option and I know many will love it  but unfortunately it is not good in this form. It's made a lot of trouble. If it can be done like in tmdb helper then it will be great. I still hope you find some way to sort out this option.

**Comment by antonsoroko** [comment]
ok, lets remove it for non-library items.

in a meantime i found a bug with "Show number of unwatched episodes" - even with tmdb as a source code still made requests to trakt and thus slowness.

**Comment by matke-84** [comment]
@antonsoroko This then explains why it takes so long to load.

**Comment by antonsoroko** [comment]
okay. i made PR with all fixes. i hope new release will be ok.

**Comment by matke-84** [comment]
@antonsoroko Great. I am very sorry for these functions choose artwork, but I hope that you and @elgatito will find a better and easier way to implement them. Will there be an update today?

**Comment by matke-84** [comment]
@antonsoroko Did you manage to fix the "Show number of unwatched episodes" episodes slow loading?

**Comment by antonsoroko** [comment]
Yes, see PR above.

**Comment by matke-84** [comment]
@antonsoroko I'm sorry, I'm looking at the phone, so I didn't see it well. Can we expect some urgent update given the fact that the elementum is not working properly at the moment?

**Comment by antonsoroko** [comment]
it is not up to me. when author will have free time - he will do release.

**Comment by matke-84** [comment]
Ohhh. OK. Thanks.

**Comment by ThurahT** [comment]
Yeah, this update totally prevent any kind of playback on my kodi 17.6. I have an almost barebone installation. Only core stuff and trakt plus elementum and burst.

In my opinion the last elementum I had no issues with was 0.1.76. I was so miffed yesterday not being able to watch my already downloaded seasons (I use all files) I tried to clean cahes, clean, torrents, databases. Nothing helped (since that helped the issue I had with 0.1.77 see closed bug).

I then tried to just start from beginning with an empy .kodi/ directory. Fresh install 0.1.79 and after setting trakt and subtitles addons up it was time to install elementum 0.1.79 and guess what?

Just keeps crashing. I'm so mad. Can someone just link me the 0.1.76 release so I can have my media center back?

**Comment by matke-84** [comment]
@ThurahT https://github.com/elgatito/plugin.video.elementum/releases/tag/v0.1.76

**Comment by matke-84** [comment]
@ThurahT You have no reason to be angry. @elgatito and @antonsoroko do this completely free of charge for all of us and it should be respected.

**Comment by ThurahT** [comment]
I know how FLOSS works. It doesn't prevent me from being miffed when I've prepared an evening and nothing works.

**Comment by antonsoroko** [comment]
If you had your files already downloaded as you said - you could have simply watched them directly in kodi, from elementum's download directory.

**Comment by ThurahT** [comment]
There was nothing in left in elementums directories since I had tried "fixing" the mess with what helped me last time. Cleaning out caches and torrents.

Sure I could play them in mpv outside of kodi. But what's the point of kodi then? It's the trakt and tmdb integration that makes it a media center for me.

I am trying to install and set up all accounts now along with a fresh 0.1.78 install and see if I can get this up and running as it used to.

A question. If I get it up and running again can I still update context helper and burst as usual since I will never again update elementum? Or will something break eventually if I keep ignoring elelmentum updates?

**Comment by antonsoroko** [comment]
>Sure I could play them in mpv outside of kodi.

I meant you could have used the Kodi itself to play a video. But yes, trakt sync would have been temporarily unavailable.
Also, even if you decided to delete everything, you could have deleted torrents without files, in order to have a backup plan.

>since I will never again update elementum?

Honestly, I do not even want to answer a question like this. I hope you understand that this statement is simply disrespectful.
You could have asked a technical question without declaring you feelings or intentions.
If you wanted to ask hypothetical question then you should have phrased it correctly (e.g. by using "if" instead of "since").

Anyway, burst is loosely coupled with elementum, context is tightly coupled.

**Comment by antonsoroko** [comment]
@matke-84 
>OK. I didn't know that. In that case, I will not be able to use it in widgets, but only directly in elementum.

if https://github.com/elgatito/context.elementum/pull/21 and https://github.com/elgatito/elementum/pull/75 will be merged then it will work for widgets as well.

**Comment by ThurahT** [comment]
I meant no disrespect. I am also not a native english speaker. Since and if is basically the same in my language.

I am glad that there is work being done on elementum. Think no nothing else, but perhaps we should have a beta channel for your new features and a stable for people who wants noting else than watch their shows with trakt and tmdb integration?

**Comment by matke-84** [comment]
> @matke-84
> 
> > OK. I didn't know that. In that case, I will not be able to use it in widgets, but only directly in elementum.
> 
> if [elgatito/context.elementum#21](https://github.com/elgatito/context.elementum/pull/21) and [elgatito/elementum#75](https://github.com/elgatito/elementum/pull/75) will be merged then it will work for widgets as well.

That's good news. 👍

**Comment by antonsoroko** [comment]
>but perhaps we should have a beta channel for your new features and a stable for people who wants noting else than watch their shows with trakt and tmdb integration?

that would be great i think.
we already have a gitter chat https://gitter.im/ElementumApp/Lobby for communication (but this chat is "silent" for a long time).
the only thing is to find beta testers :-)
also i am not sure if it will be convenient for author to make beta builds.

but in general it would be great to have beta testers.

**Comment by antonsoroko** [comment]
okay. new elementum release is live. thanks to author.
please test.

also context addon was released.

**Comment by antonsoroko** [comment]
scratch that. new issue.

**Comment by antonsoroko** [comment]
https://github.com/elgatito/plugin.video.elementum/pull/799

**Comment by antonsoroko** [comment]
0.1.81 should be ok.

**Comment by matke-84** [comment]
@antonsoroko For now everything works fine. "Show number of unwatched episodes" is much, much faster. Mark as watched in trakt from elementum context menu works with widgets. Network studio for tv shows also works. All movies and tv shows can watched. All skin functions work again. Do not worry. Everything is ok now. Thanks a lot for the new stuff. My only regret is that choose artwork does not work, but I know that you and @elgatito will find a solution for that as well. Thanks again for everything. 😉

**Comment by antonsoroko** [comment]
@matke-84 
Thank you for testing.

>"Show number of unwatched episodes" is much, much faster. 

Btw, it takes basically the same time as without it. Overhead is about 10 milliseconds with tmdb, because tmdb provided all data about tv show in 1 call. with trakt it will take much more time since we had to make several additional calls to get seasons and episodes inside seasons.

**Comment by matke-84** [comment]
> 
> 
> @matke-84
> Thank you for testing.
> 
> > "Show number of unwatched episodes" is much, much faster.
> 
> Btw, it takes basically the same time as without it. Overhead is about 10 milliseconds with tmdb, because tmdb provided all data about tv show in 1 call. with trakt it will take much more time since we had to make several additional calls to get seasons and episodes inside seasons.

@antonsoroko Yeah, it works fast as without this option. Really good job. 👍
