### ISSUE TITLE
[Bug] Disabling Trakt sync options doesn't work properly

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#825]
Hi,
@elgatito 
@antonsoroko

Following this issue: https://github.com/elgatito/plugin.video.elementum/issues/823

**Steps:**

1) Configure these settings in Elementum:
* Kodi Library -> Maintenance -> Enable Kodi library synchronization - **True**
* Trakt -> Synchronization - > sync items from collections & watchlist & user lists into Kodi Library - **False**

2) Close Kodi.

3) The bug is regarding the Shows library path in Elementum: "userdata\addon_data\plugin.video.elementum\Shows"
So empty the folder. 
Make sure you have content in Trakt (I have both on my shows collection and my user list.)

4) Start Kodi, and keep watching on the shows library folder.

**The bug:** 
Content still comes from trakt sync even though I disabled it (35 folders of shows)
My Shows Collection  in Trakt has: 52 items.
My shows list in trakt has: 30
But again, I disabled these options, so I don't expect to get any data on this case.
* It seems that with Movies library path it's ok and doesn't have this problem.

**Extra info:**
Kodi debug log: https://paste.ubuntu.com/p/zBVSFqfK6w
My Elementum settings.xml: https://paste.ubuntu.com/p/wQTMj3s8fM

**My goal is:**
As we discussed on the another issue, my purpose is to be able add content to the library path manually by selecting an item and using the "Add to library" in the context menu, and keep Elementum to be able to identify that so I be able to see the "Remove from library" option when selecting an item in Elementum which already exist in my Kodi Library.

Thanks.

---

Tested with:
Elementum 0.1.83
Kodi 19.1 (Matrix)
Windows 10

**Comment by elgatito** [comment]
@burekas7 It is not coming from Trakt.
Once something is added from Elementum to Kodi library, then Elementum updates strm files in those directories, according to TMDB changes. 
Even if you remove directories - information about added shows is stored in the database of Elementum.

**Comment by antonsoroko** [comment]
@elgatito btw, is there a way to delete this "orphaned" information from elementum's database?
i think this would solve many issues that @burekas7 has.

**Comment by elgatito** [comment]
@antonsoroko 
I guess you can go to Movies -> In library (in the end of the list), it would shows you everything that Elementum is having in internal library, so there you can remove something in default context menu.

**Comment by burekas7** [comment]
@elgatito 

I found the problem.

Some questions:
1. What is the difference between the options in the menu: "In Kodi Library" and "In Elementum Library"?
2. Pressing on "In Kodi Library" doesn't do anything, just refresh the menu.
3. Pressing on "In Elementum Library" shows only these extra 5 TV Shows that I mentioned above. Why only they appear there?
4. In addition to (1) Why when I enable the "Enable Kodi library synchronization" does it take these TV Shows from this "Elementum Library" and adds them to Kodi? What is the purpose of "Elementum Library"?

**Comment by elgatito** [comment]
1. "Elementum library" is what Elementum has in internal library. That should be synced to Kodi, but it is Kodi task to scrape and import strm files. "In Kodi library" is what we get from Kodi and it is imported from Elementum (not the full library).

2. If you have not enabled library integration - then there are no items received from Kodi. It should probably show empty list.

3. When you click in Elementum "Add to library" on a show/movie - it gets added to internal library and strm files are created for Kodi. Even if Kodi is not reading files - you will have them in Elementum's library, so that when you change library path in settings - we can write strm files for everything that you were adding before - to a new library path.

4. "Enable Kodi library synchronization" is a setting whether we should initiate Kodi library updates. That is used to say Kodi that there are new strm files to be parsed. 

5. "Merge to library" - re-write strm files on the disk. "Remove from library" - remove from local Elementum library and remove strm files. "Return to TV shows" - just a browsing redirect to send you to TV Shows menu.

Elementum cannot control Kodi media sources, modify them (and even get list of sources).
All Elementum can do - is write somewhere files and hope someone added that path as a source for Shows/Movies.
Once we remove something from disk or add something - we can ask Kodi to start library check to pick up new files.

**Comment by burekas7** [comment]
@elgatito 
Thanks.

So if I "Remove from Library" in Kodi Library, does it removes also from Elementum Library?
Is this may be the reason there was "leftover" Tv Shows in Elementum Library?

What is the right way to remove a TV Show / Movie from Kodi Library?
Should I need always remove it on both places, Kodi Library & Elementum Library?
