### ISSUE TITLE
can't write to mounted NAS folder despite proper permissions

### ISSUE THREAD

**Issue by dullibert** [elgatito/plugin.video.elementum#870]
using Kodi on Nvidia Shield, I have an issue with selecting a mounted network drive from my synology nas as the download location in elementum. In other apps, like file browsers (e.g. x-plore), I can write and save files without a problem, but in Kodi/Elementum I get "open /store/NAS/folder/.writeable: permission denied" 

how can I fix this?

**Comment by ShlomiD83** [comment]
How did you mount the network share?
through Kodi? Shield settings?

**Comment by Ariancabef** [comment]
> using Kodi on Nvidia Shield, I have an issue with selecting a mounted network drive from my synology nas as the download location in elementum. In other apps, like file browsers (e.g. x-plore), I can write and save files without a problem, but in Kodi/Elementum I get "open /store/NAS/folder/.writeable: permission denied"
> 
> how can I fix this?

same problem here. I can access my local NAS (added in Kodi) collection in Shield/Kodi without any problem but Elementum can't use the external storage as download location.

any idea?

**Comment by elgatito** [comment]
It is not possible, because Kodi is managing NFS/Share on it's own. If you expect same from Elementum - then it should also deal with NFS/shares inside, which is not possible, because torrents are managed by third-party library.

To make this work - you should add NFS/Share in the system (not in Kodi), so that it would look like a usual folder in the system.

In this case system will manage how to write/read to those locations.
