### ISSUE TITLE
Crash daemon, auto choose stream, progress in library

### ISSUE THREAD

**Issue by denisNic** [elgatito/plugin.video.elementum#89]
## Current Behavior
1. Not working progress "Watched" in the library and crash daemon
2. Not working "Choose stream automatically"

## Possible Solution
1. not use parametr "uniqueid"

## Steps to Reproduce (for bugs)

1. [mark] Include the series and watch until the end
1. [crash] include any stream in elementum or library, rewinding to the end, press stop or wait until the end
2. Choose the stream automatically in the context menu elementum

## Context
1. Work progress "Watched" in the library
2. Working cover for series in the library while browsing
3. Fix crashes daemon
4. Fix auto choose stream
## Your Environment

* Version used: Elementum 0.0.40, Burst 14
* Environment name and version: Kodi 16.1 [Jarvis] 
* Operating System and version: Windows 8.1 x86
* Link to Kodi debug log:

1. [library and Crash](https://paste.ubuntu.com/26502609/)
2. [Choose stream auto](https://paste.ubuntu.com/26502653/)

**Comment by elgatito** [comment]
> Crash daemon, 

Issue was fixed in torrent engine.

> auto choose stream, 

I have checked and it is working as expected. If you select "choose automatically" and start something from plugin - it will start automatically, if you open context menu - you will have an opposite action (if autoselect enabled - will open list of links). If you start from Kodi library - it reads what to do from strm file. In this case you can enable "Force stream selection ... ", that makes sure strm if not influencing play/links selection.

> progress in library

Moved uniqueid, premiered into another call. Your Kodi 16 is too old, it would work better if you run newer 16.* Kodi.

**Comment by denisNic** [comment]
[auto choose streem] 
If you select "choose stream automatically" in the settings, then in the library this only works after the restart. If you select "force stream auto selection", it does not work from the context menu, but I would like to start automatically
[progress in library]
16.*? 16.1 last build, next only 17.
If I could use 17[krypton], I would use it, there the progress works long ago
I would like compatibility with 16.1 build
