### ISSUE TITLE
Elementum not opening LG webOS nightly build Kodi 21 _ again

### ISSUE THREAD

**Issue by TulipVang** [elgatito/plugin.video.elementum#951]
Hi, any body can help to run elementum in webos nightly Kodi.

I saw a issue earlier but I could not use what was saying there
I could install the repository of elementumorg but when install addon, it did not open elementum properly.
Hope I can have a detail instruction to run elementum.

**Comment by TulipVang** [comment]
I also tried to install ldd ipk from entware repository but the opkg return "open outer: fail to open package... Unrecognized archive format"

**Comment by TulipVang** [comment]
I referred to the previous issue
https://github.com/elgatito/plugin.video.elementum/issues/939

**Comment by antonsoroko** [comment]
@TulipVang start by providing log file, see https://github.com/elgatito/plugin.video.elementum/issues/939#issuecomment-1653353625

also, you can ask @A-Shahbazi and @sharkticonnz if they have any issues. I think they are the only ones webos users here. But looks like elementum works for them.

**Comment by sharkticonnz** [comment]
Hey TulipVang, Yeah Elementum works on my end using nightly builds of LGWebOS. How I got it to install was.

1. Installed an official kodi addon ( I used south park )
2. downloaded [armv7_softfp](https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.98/plugin.video.elementum-0.1.98.linux_armv7_softfp.zip).
3. Using WebOS dev manager uploaded it to a place I could find navigating through kodi.
4. install from Zip as per usual.

Big shout out to @elgatito , @antonsoroko and @A-Shahbazi as with out there assistance I wouldnt have it up and running.

**Comment by TulipVang** [comment]
@sharkticonnz 
My TV is rather old with limited storage. So I had to root it to offload Kodi to usb to try install elementm from armv7_softfp. However, it still didn't start.
As it is rooted, if i install developer mode, root and kodi will be gone. I have to upload homebrew and kodi again and limited storage will prevent installing armv7_softfp.
Let me try upload armv7_softfp by Filezilla to install zip again tonight. It is morning now in my time.

**Comment by TulipVang** [comment]
> @TulipVang start by providing log file, see [#939 (comment)](https://github.com/elgatito/plugin.video.elementum/issues/939#issuecomment-1653353625)
> 
> also, you can ask @A-Shahbazi and @sharkticonnz if they have any issues. I think they are the only ones webos users here. But looks like elementum works for them.

Thank you. I will try what @sharkticonnz suggested and come back.

**Comment by TulipVang** [comment]
@A-Shahbazi
Can you help to install the ldd ipk please

**Comment by antonsoroko** [comment]
@TulipVang you do **not** need `ldd` to run elementum. it was needed for initial troubleshooting of #939.

and "**start by providing log file**". nobody can help you without log.

**Comment by TulipVang** [comment]
@antonsoroko I tried to install log uploader but it also failed.

**Comment by antonsoroko** [comment]
@TulipVang do it manually then: https://kodi.wiki/view/Log_file

although, if even simple addon like "Kodi Logfile Uploader" does not work - i doubt that anything will work, especially complex addon like elementum.

do other addons work?
if not - maybe you need to update your webos or something like this. you can ask on some webos forum about how to make kodi work on your tv.

**Comment by TulipVang** [comment]
> @TulipVang do it manually then: https://kodi.wiki/view/Log_file
> 
> although, if even simple addon like "Kodi Logfile Uploader" does not work - i doubt that anything will work, especially complex addon like elementum.
> 
> do other addons work? if not - maybe you need to update your webos or something like this. you can ask on some webos forum about how to make kodi work on your tv.

As I checked, some add on still can be installed and work. I can watch simple iptv client as usual.

**Comment by antonsoroko** [comment]
Ok.
1. Try to manually set "platform" to **linux_armv7_softf** in elementum settings
2. Provide log file

**Comment by TulipVang** [comment]
I will try to find log file here
/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/temp
Source from https://github.com/xbmc/xbmc/blob/master/docs/README.webOS.md

**Comment by TulipVang** [comment]
@sharkticonnz I would like to attach the log. Kindly help to review. Thank you
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/13337006/kodi.log)

**Comment by sharkticonnz** [comment]
@TulipVang Hey mate comparing my log to yours, Your one seems to get stuck and crash because of your remote controller (I think) have you got HDMI CEC enabled? try again with it turned on. https://www.lg.com/us/support/help-library/lg-tv-how-to-enable-hdmi-cec-CT10000018-20153164607551

**Comment by TulipVang** [comment]
> @TulipVang Hey mate comparing my log to yours, Your one seems to get stuck and crash because of your remote controller (I think) have you got HDMI CEC enabled? try again with it turned on. https://www.lg.com/us/support/help-library/lg-tv-how-to-enable-hdmi-cec-CT10000018-20153164607551

Hi. Actually, HDMI CEC is on. I turned it off and on again, install the elementum from repo but it still crashed. I tried to install from softfp but I lost ssh connection to upload, will try another time.

**Comment by TulipVang** [comment]
@sharkticonnz
I upload the log file again.
Please help to review. Many thanks
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/13350234/kodi.log)

**Comment by antonsoroko** [comment]
@TulipVang 

1.
>This time I install addon from softfp zip file.

so, before you tried to install regular version of elementum?
to make it clear: **only** softfp will work on webos and you need to install it **explicitly** via zip file and by setting "platform" to **linux_armv7_softf** in elementum's **settings**.

2. btw, maybe you need to use "nightly builds of LGWebOS" as **sharkticonnz** suggested.

3.
>As log file said some file like urllib3 missing

many addons use urllib3 module. strange that it failed to install.

>Now my kodi stop working right at the start :(

if you are tech savvy then you can try to see what kodi says in log, and maybe try to uninstall urllib3 manually (delete files).
but anyway, to run elementum you would need to install urllib3 somehow.
maybe consider complete re-installation of kodi.

**Comment by TulipVang** [comment]
I will try to install kodi again.
However there is one thing I don't understand.
How can I do the setting "platform" in elementum setting?

**Comment by antonsoroko** [comment]
1. install linux_armv7_softf zip
2. open elementum settings (even if it fails to start - you still can open settings)
3. in the first tab ("general") - change platform from "auto" to "linux_armv7_softf"

**Comment by TulipVang** [comment]
I changed the platform as you guided.
But installation behavior did not change. It kept failing. 
I send the log file if you have any suggestion. Thank you
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/13359346/kodi.log)

**Comment by antonsoroko** [comment]
1. i do **not** see in log that you use **linux_armv7_softf**. maybe i am wrong, but looks like you still try to use linux_armv7 (which will not work as was said many times).
2. maybe because you **rooted** your device it behaves strange. 
type `mount` in terminal/ssh and share output.
also try to run `chmod +x /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum` - this command fails in log.
and `chmod +x /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7_softf/elementum` when you finally install proper version linux_armv7_softf.
3. `No module named 'kodi_six'` in log. either find a way to install it or install **kodi 20** (not 21).

**Comment by TulipVang** [comment]
> 1. i do **not** see in log that you use **linux_armv7_softf**. maybe i am wrong, but looks like you still try to use linux_armv7 (which will not work as was said many times).
> 2. maybe because you **rooted** your device it behaves strange.
>    type `mount` in terminal/ssh and share output.
>    also try to run `chmod +x /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum` - this command fails in log.
>    and `chmod +x /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7_softf/elementum` when you finally install proper version linux_armv7_softf.
> 3. `No module named 'kodi_six'` in log. either find a way to install it or install **kodi 20** (not 21).

I just did reinstall kodi; then install linux_armv7_softf, chmod the elementum of linux_armv7_softf
I would like to upload mount and log for your support please
[Mount.txt](https://github.com/elgatito/plugin.video.elementum/files/13364509/Mount.txt)
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/13364510/kodi.log)

**Comment by antonsoroko** [comment]
@TulipVang sorry, but it is very hard to help you, because:
1. looks like only now you finally installed linux_armv7_softfp - so before that we just wasted time. 
2. for simple errors - i am pretty sure that you can read log file by yourself - it clearly says `[Errno 28] No space left on device`
3. **after** you deal with space: for `chmod` - i wanted to see command output, obviously. but for correct path. **if** you will see in log something like:
```
error <general>: os.chmod(file_, st.st_mode | stat.S_IEXEC)
error <general>: PermissionError
error <general>: [Errno 1] Operation not permitted: BINARY_PATH_IS_HERE
```
then run `chmod +x BINARY_PATH_IS_HERE` and post output here.

4. **if** you will see in log `No module named 'kodi_six'` - then either find a way to install it or install kodi 20 (not 21).

**Comment by TulipVang** [comment]
@antonsoroko Thank you very much.
4. I think kodi_six can be solved first. I install from zip download for omega at https://mirrors.kodi.tv/addons/omega/script.module.kodi-six/
It should be OK

2 & 3. Two might be connected. Elementum using the .kodi folder from other position than the .kodi folder I mounted when I offloaded kodi to usb to solve the no space issue-if my understanding is correct.
The mounting is saved in a script at /var/lib/webosbrew/init.d/ to run at least when the homebrew channel is opened, I would like to attach if you can suggest how I can mount the both .kodi folder to the same .kodi folder in usb?
[kodi1.zip](https://github.com/elgatito/plugin.video.elementum/files/13366689/kodi1.zip)

**Comment by antonsoroko** [comment]
@TulipVang i do not know anything about webos apart that it is linux based.

but i guess `/var/palm/jail/org.xbmc.kodi/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi` (from your script) and `/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi` (from kodi log) are the same. you can create file in 2nd directory and check if it present in 1st directory. 

anyway - elementum uses `.kodi` directory provided by kodi itself.
so if something is wrong with `.kodi` - it is because of wrong configuration, not because of elementum.
from your kodi log:
`2023-11-15 22:27:20.860 T:1555     info <general>: special://home/ is mapped to: /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`

also as you can see in log - now you have `[Errno 1] Operation not permitted`.

and if you look into output of `mount` you will see (from txt file above):
`/dev/sda4 on /var/palm/jail/org.xbmc.kodi/tmp/usb/sda/sda4 ...`

looks like your mount is wrong. you get `/var/palm/jail/org.xbmc.kodi/tmp/usb/sda/sda4` instead of `/var/palm/jail/org.xbmc.kodi/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`

maybe try:
`mount -o bind /tmp/usb/sda/sda4/.kodi /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`

if it will not work - actually, you do not need "to mount", you can simply use links. like:
`ln -sf /tmp/usb/sda/sda4/.kodi /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`
or
`ln -sf /tmp/usb/sda/sda4/.kodi /var/palm/jail/org.xbmc.kodi/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`

(but you need to delete or move  original `.kodi` directory first, of course)

**Comment by TulipVang** [comment]
@antonsoroko thank you very much. So details.

Step by step, I can mount and chmod rather well.
Now the log return GetDirectory - Error getting plugin://plugin.video.elementum/

I send you the mount and log for your advice please.
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/13371569/kodi.log)
[mount_chmod.txt](https://github.com/elgatito/plugin.video.elementum/files/13371571/mount_chmod.txt)

**Comment by TulipVang** [comment]
@antonsoroko 
I can install elementum and start it now. However, Burst failed to install. From log, I can see future dependency cannot install.

2023-11-16 11:02:58.168 T:1465    error <general>: Copy - Failed write to file /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/temp/7b437f36-ea0e-48ec-ad90-5205857c4a2a/icon.png
2023-11-16 11:02:58.169 T:1465    error <general>: Failed to unpack archive 'zip://%2ftmp%2fusb%2fsda%2fsda4%2fscript.module.future-0.18.2%2bmatrix.1.zip/script.module.future/' to '/media/dev

**Comment by TulipVang** [comment]
I think the error occurred due to no space even though some message saying that due to wrong structure.
I will manually delete some PVR that I don't use to get more space tomorrow.

**Comment by antonsoroko** [comment]
if after `mount` you still has issues with free space - maybe it have not worked?
i mean, i expect that your hdd has free space.
check that you really mounted hdd to proper path (to `.kodi` directory, i mean).
for example, create big files in `/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi`.

if you can't make `mount` work - you can try to use links (`ln` command from above).

**Comment by TulipVang** [comment]
Yes. It works now.
The only problem is space. Enough space then it is done with armv7_softfp.
For safety, I still kept install the kodi-six first. But if enough space, I think it should run well without this step as well. 
Sometimes the system can message thing like wrong structure but the real cause is not enough space to unpack archive which consequently cause the wrong structure.
Thank you very much for follow up and support. I really appreciate.

**Comment by antonsoroko** [comment]
@TulipVang 
>The only problem is space.

i still recommend you to check if you really use hdd. unless you do not have enough free space on hdd too.

**Comment by TulipVang** [comment]
Yes. I stop using the usb. Even after finishing Elementum installation and successful start, offload Kodi to usb making Elementum cannot start. Now I just run minimum Kodi with Elementum + opensubtitle, other space of webos for ssIptv for me and YouTube adfree for my kids.
