### ISSUE TITLE
[Request] Add a confirmation dialog for "Delete" options in Context menu

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#961]
Hi, @elgatito 

Currently, there is no confirmation dialog when pressing on anyone of the "Delete" options in Elementum Context menu in the Torrents list.

Relates to:
* Delete torrent
* Delete torrent and files

I think it was in the past.
So if you can add this it would be nice.

Thanks.

---
Elementum 0.1.98

**Comment by elgatito** [comment]
There is no confirmation because you need to somehow get to that action and click on it and then your settings come into play, where you can set to have a confirmation for removing torrent files.

**Comment by burekas7** [comment]
> There is no confirmation because you need to somehow get to that action and click on it and then your settings come into play, where you can set to have a confirmation for removing torrent files.

I don't understand what you actually said.
But I can tell that it was there in the past, you can see an old issue that I had with that dialog when pressing on "Delete" option in the context menu:
https://github.com/elgatito/plugin.video.elementum/issues/529

**Comment by antonsoroko** [comment]
@burekas7 i took a look into the code and there is confirmation. BUT:
1. you must enable it in settings.
https://github.com/elgatito/plugin.video.elementum/blob/79f7828b73ef965b1c5762eda0a06d7422c85a88/resources/settings.xml#L61-L63
2. it only works for "delete", not for "delete with files" (in this case deletion of files is forced, see below)

logic is described here https://github.com/elgatito/elementum/blob/96de9daa7bbb278e52a4a6cecc06a04bd3364751/bittorrent/service.go#L920

also it is important to note that this `RemoveTorrent` function will ask you if you want to delete `.torrent` file from queue and then it will ask you if you want to delete video files.
so "delete" is a shortcut for "RemoveTorrent" that answer "yes" to first questions.
so "delete with files" is a shortcut for "RemoveTorrent" that answer "yes" to both questions.

and this RemoveTorrent function is also invoked when you closed video (with unfinished and finished progress).
so depending on your settings it will ask to delete .torrent and files.

---

in order to always show a confirmation for "Delete torrent and files" we would need to:
1. if you have confirmation is settings (default value)
a. for "delete" - delete torrent and ask to delete files (like we have now)
b. for "delete with files" - delete torrent and ask to delete files (so it will be the same as "delete" menu, unlike now)
2. if you disabled confirmation and said to keep downloading and keep unfinished/finished videos in settings:
a. for "delete" - delete torrent and keep files (no question, like we have now)
b. for "delete with files" - delete torrent and ask to delete files (new behavior)

not sure if "delete with files" menu will be useful after such changes.
i guess in this case we also need to make  "delete" not to ask about files deletion, otherwise those 2 menu items will be the same.
or we need to leave only "delete" menu item, and it will always ask about files deletion.

CC: @elgatito

**Comment by antonsoroko** [comment]
@elgatito what about
we leave only "delete" menu item, and it will always ask about torrent deletion and files deletion. for example, qBittorrent and Deluge clients use this approach. 
?

maybe this approach will more safe and it will not be affected by playback-related options (i mean these options: keep downloading after stop, keep torrent after complete/incomplete playback).

alternatively, Transmission has both menu item but also asks confirmation for both item ("delete" and "delete with files").
but anyway it is good idea to always ask in menu regardless of playback-related options.

**Comment by antonsoroko** [comment]
@elgatito i mean: **only** for context menu we can always ask about deletion. 
the idea is to separate context menu (in torrents list) from playback-related settings, b/c they have different user experience.


we can leave 1 menu item (delete) and ask twice ("delete torrent?", then "delete files?").
if "delete torrent?" - yes - we delete torrent and ask "delete files?".
if "delete files?" - yes - we delete files, if "no" - we keep files.
if "delete torrent?" - no - we do not delete anything and we do not ask about files.

or we can keep 2 menu items (delete, delete with files) and ask 1 confirmation about deletion.
if "delete" - ask and if "yes" remove torrent only , if "no" - do not delete anything.
if  "delete with files" -  ask and if "yes" remove torrent+files , if "no" - do not delete anything.

**Comment by antonsoroko** [comment]
@elgatito i made a [PoC](https://github.com/elgatito/elementum/pull/143) of 1st approach - code does not looks "polluted", imho, so i think it is ok, but of course it is up to you to decide.
