### ISSUE TITLE
Playback failed  ,No links were found 

### ISSUE THREAD

**Issue by ajay01994** [elgatito/plugin.video.elementum#981]
Hii @elgatito 

Firstly i would like to express my gratitude to you for  open sourcing your work and even if you have mentioned that the development has stopped and dont expect fast support you still go out of your regular call of duty to help resolve issues,so thanks a lot ! it really helps a lot of us .  i have been using elementum for quite few years now and it worked fine .yesterday i updated my kodi version from( 20.2 )to (20.3 )and burst cannot find links from the TV shows etc links and  ,however when i copy magnet link in elementum and paste  it works .i am using the latest version of elementum . no chnages have been made on my end the proxy setting have been same throughout ,looking forward for your help ..

Thanks in Advance ..

**Comment by antonsoroko** [comment]
when you created issue there was the template, that template has the link to the guide about how to create a log file.
it is impossible to understand your issue without log file.

**Comment by antonsoroko** [comment]
@ajay01994 if you will open that log you will see hundreds of 
`Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))`

so looks like your proxy is dead (or you computer can't reach your proxy for some reason). i also can not connect to proxy IP that i see in log.

it is not a script.elementum.burst addon issue, but network issue on your side.

**Comment by ajay01994** [comment]
Thanks for taking out your valuable time to look at the logs and letting me know about the possible issue . Could you help me in giving some guidelines over settings up proxy in elementum or solutions around it ?

Thanks in advance

**Comment by antonsoroko** [comment]
I do not understand what you mean. Either disable proxy if you do not need it (e.g. your ISP do not block torrent sites) or use a new proxy. As I said - the proxy you currently use is dead (as i can see).

**Comment by elgatito** [comment]
@ajay01994 
1) This is not the correct place for issues related to search addons. For Burst related issues use Burst repository - https://github.com/elgatito/script.elementum.burst/issues
2) There are connectivity issues for at least one provider, and it was causing you to wait for timeout to happen.
3) Check your Burst settings whether any proxy is used, because your log has many errors saying it cannot connect to a proxy. Also you can try to disable Elementum as a proxy in Burst settings.
4) Use latest Burst 0.0.83 version, that should ignore failed providers and cause a timeout.

**Comment by ajay01994** [comment]
Hi guys ..

After updating burst 2 providers are coming now ..which is better however a lot of them are still not coming there is no change in proxy settings as it remains the same I am using libreelec .moving the conversation to burst issue
